### ISSUE TITLE
Подскажите, как мне ограничить минимальный размер порезанного изображения?

### ISSUE THREAD

**Issue by ferz222** [ruslanskorb/RSKImageCropper#100]
Привет, мне в проекте необходимо, чтобы порезанные изображения были не менее 450x450. Как мне это можно сделать, очень надо?

**Comment by ruslanskorb** [comment]
Hi @ferz222,
I think [that's](https://github.com/ruslanskorb/RSKImageCropper/issues/52) what you need.

**Comment by ferz222** [comment]
Thank you, I already is found and made.
