### ISSUE TITLE
Pure Circle

### ISSUE THREAD

**Issue by pjebs** [ruslanskorb/RSKImageCropper#101]
Since the original image is usually a rectangle, sometimes if the user zooms out too much, the original image runs out of 'image' on the sides.

Hence the resultant cropped image is also a rectangle rather than a square.

How can I prevent the user from zooming out too much to force the resultant image to be a square?

**Comment by jquiambao** [comment]
I think this might be the property you're looking for:

`[RSKImageCropViewController avoidEmptySpaceAroundImage]`

Just set that to YES,
