### ISSUE TITLE
Image cannot be moved with Custom Rect and avoidEmptySpaceAroundImage=YES

### ISSUE THREAD

**Issue by gmogames** [ruslanskorb/RSKImageCropper#102]
Hello there!

I'm using RSKImageCropper on a project and I noticed that when I use a custom rect mask with avoidEmptySpaceAroundImage=YES, I cannot move the image until I try to zoom in or out. After zooming out/in then the image can be moved correctly even though it's the same size as when loaded.

Example: http://valeconsulta.com.br/cropper.gif

My Code:
```
- (void) openCropper:(UIImage *)image{
self.imageCropVC = [[RSKImageCropViewController alloc] initWithImage:image cropMode:RSKImageCropModeCustom];
    self.imageCropVC.delegate = self;
    self.imageCropVC.dataSource = self;
    self.imageCropVC.maskLayerColor = [UIColor KOGreenColor:0.8];
    self.imageCropVC.avoidEmptySpaceAroundImage = YES;
[self presentViewController:self.imageCropVC animated:YES completion:nil];
}

- (CGRect)imageCropViewControllerCustomMaskRect:(RSKImageCropViewController *)controller
{
    CGSize maskSize;
    CGRect fullScreen = [[UIScreen mainScreen] bounds];
    maskSize = CGSizeMake(fullScreen.size.width - 20, fullScreen.size.height - 60);
    
    CGFloat viewWidth = CGRectGetWidth(controller.view.frame);
    CGRect maskRect = CGRectMake((viewWidth - maskSize.width) * 0.5f,
                                 10,
                                 maskSize.width,
                                 maskSize.height);
    
    return maskRect;
}

// Returns a custom path for the mask.
- (UIBezierPath *)imageCropViewControllerCustomMaskPath:(RSKImageCropViewController *)controller
{
    CGRect rect = controller.maskRect;
    UIBezierPath *area = [UIBezierPath bezierPathWithRoundedRect:rect cornerRadius:10];
    
    return area;
}

- (CGRect)imageCropViewControllerCustomMovementRect:(RSKImageCropViewController *)controller{
    return controller.maskRect;
}
```

**Comment by ruslanskorb** [comment]
Hi @gmogames!
I have checked your test case using my photos. But everything works as expected. Can you provide an example project with the photo you use?
Thanks!

**Comment by gmogames** [comment]
Hi @ruslanskorb ,

I separated the part of the code from my original project. Even though there is a slight difference (the image starts real big), you can see the problem by trying several photos and panning.

PS: Thanks for the help

[CropperExample.zip](https://github.com/ruslanskorb/RSKImageCropper/files/163804/CropperExample.zip)

**Comment by ruslanskorb** [comment]
You have specified an incorrect movement rect.
I think in your case you can use `maskRect` as `movementRect` and everything will work as it should.

```obj-c
- (CGRect)imageCropViewControllerCustomMovementRect:(RSKImageCropViewController *)controller
{
    return controller.maskRect;
}
```

**Comment by gmogames** [comment]
Weird, It does fix the problem on the project I put up for you, but doing the change on my project, which is the exact same code and files, it doesn't work :( I'll keep digging, thanks for your help!

**Comment by gmogames** [comment]
@ruslanskorb I've been debugging this, and in the project that works, the properties of RSKImageScrollView is:

```<RSKImageScrollView: 0x7ffd7b8cea00; baseClass = UIScrollView; frame = (10 10; 355 607); gestureRecognizers = <NSArray: 0x7ffd7de84e20>; layer = <CALayer: 0x7ffd7de6bd10>; contentOffset: {126, 0}; contentSize: {607, 607}>```

and for the project that doesn't work is:

```<RSKImageScrollView: 0x7fd30e06ba00; baseClass = UIScrollView; frame = (10 10; 355 607); gestureRecognizers = <NSArray: 0x7fd30bcad080>; layer = <CALayer: 0x7fd30bca5cf0>; contentOffset: {20, 0}; contentSize: {375, 607}>```

I'm using the same image, the same code, everything the same. Have any idea how the ContentOffset and ContentSize would get different values?

**Comment by gmogames** [comment]
Nevermind. I had another lib I was using that had a UIScrollview category that was hijacking the setContentSize method and interferring with your lib. Took me a long time to find it.

Thanks for all your help!
