### ISSUE TITLE
How to force cropping and avoid taking all the Image !

### ISSUE THREAD

**Issue by genius50** [ruslanskorb/RSKImageCropper#103]
Hello there !

How to prevent the user taking all the image and force square cropping ? 

`imageCropVC = RSKImageCropViewController(image: image, cropMode: RSKImageCropMode.Square)`

![img_3582](https://cloud.githubusercontent.com/assets/11290656/13643159/c9b1d404-e61f-11e5-992e-c12707b1bb7c.jpg)

**Comment by ruslanskorb** [comment]
Hi @genius50!

Try to set the property `avoidEmptySpaceAroundImage` of `imageCropVC` to `true`.

**Comment by genius50** [comment]
Works perfectly, thanks
