### ISSUE TITLE
Запрещать нажатие на кнопку "Выбрать"

### ISSUE THREAD

**Issue by NikKovV** [ruslanskorb/RSKImageCropper#105]
Запрещать нажатие на кнопку "Выбрать" после единичного нажатия.

Ситуация сложилась так, что устройство не успевает среагировать и пользователь нажимает кнопку "Выбрать" два раза, в итоге получается
, что код работает два раза.

By the way, i used
- (void)imageCropViewController:(RSKImageCropViewController *)controller willCropImage:(UIImage *)originalImage {
    self.imageCropVC.chooseButton.enabled = NO;
}
- (void)imageCropViewController:(RSKImageCropViewController *)controller didCropImage:(UIImage *)croppedImage usingCropRect:(CGRect)cropRect {
...
            self.imageCropVC.chooseButton.enabled = YES;
...
}
and that fixes the problem.
It's really good API!

**Comment by ruslanskorb** [comment]
Если значение свойства `applyMaskToCroppedImage` установлено в `YES`, я рекомендую во время кропа фотографии показывать индикатор активности, который будет блокировать любые нажатия на экран. Для этой цели вы можете использовать, к примеру,  [MBProgressHUD](https://github.com/jdg/MBProgressHUD) в связке с методами `imageCropViewController:willCropImage:` и `imageCropViewController:didCropImage:usingCropRect:` делегата `RSKImageCropViewController`.
