### ISSUE TITLE
Custom rect crop fails when enabling rotation

### ISSUE THREAD

**Issue by peterdk** [ruslanskorb/RSKImageCropper#107]
I tried to crop a image with a custom rect as crop mask, but when enabling rotation, the result image is cropped in a weird way.
I read that the `imageCropViewControllerCustomMovementRect` method needs to be returning something else then the `maskRect`, but I can't figure out what I need to do. Just using the code from the square crop mode doesn't do the trick.

I would assume that a rectangular crop mask is fairly common. Are there people that have succesfully implemented this?

**Comment by fvvliet** [comment]
@peterdk : a pity no one replied, I'm also interested in an answer... Where you able to solve this in the mean time ?

**Comment by umito** [comment]
@fvvliet we disabled rotation for now. So not really a solution.

**Comment by fvvliet** [comment]
This seems to work for me...

- (CGRect)imageCropViewControllerCustomMovementRect:(RSKImageCropViewController *)controller
{
    // If the image is not rotated, then the movement rect coincides with the mask rect.
    
    CGRect rect = controller.maskRect;
    rect.origin.x -= 50;
    rect.origin.y -= 50;
    rect.size.width += 100;
    rect.size.height += 100;
    return rect;
}

**Comment by fvvliet** [comment]
This seems to work for me...

// Returns a custom rect in which the image can be moved.
- (CGRect)imageCropViewControllerCustomMovementRect:(RSKImageCropViewController *)controller
{
    // If the image is not rotated, then the movement rect coincides with the mask rect.
    
    CGRect rect = controller.maskRect;
    if (controller.rotationAngle != 0) {
        rect.origin.x -= 50;
        rect.origin.y -= 50;
        rect.size.width += 100;
        rect.size.height += 100;
    }
    return rect;
}

**Comment by Konshin** [comment]
this fixes that https://github.com/ruslanskorb/RSKImageCropper/pull/152

**Comment by SunXu231** [comment]
When I call the camera, after taking pictures, click on "use photos", present cropperController, click "cancel", the camera interface is not responding. "Remake", "use photos", buttons are not responding, the program stuck

**Comment by arcocg** [comment]
Hi, guys. I needed rotation+cropping in custom mode. So I made fast and dumb (I know) fix: instead of image rendering I used image drawing for this case. May be it'll be usefull for someone too. https://github.com/arcocg/RSKImageCropper/commit/17e77fa3839fe12dff95ceeb03c791ffaed91198

**Comment by dineshmahajan** [comment]
Thanks for share this file but this is not working when we apply rotation in app.

**Comment by Briahas** [comment]
Hi @ruslanskorb , do you have plans on fixing this bug?

**Comment by ruslanskorb** [comment]
Hi @Briahas!

This is not a bug of **RSKImageCropper**. You should calculate and return a valid movement rect from `imageCropViewControllerCustomMovementRect(_:)`.

You can see how to calculate a movement rect for the square [here](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.m#L689-L746). For all other cases, the movement rect is calculated individually.
