### ISSUE TITLE
Unable to set min zoom

### ISSUE THREAD

**Issue by thedavejay** [ruslanskorb/RSKImageCropper#108]
Hi,

Is there a way to set the minimum zoom so that the image will always have to be the width of the screen?

Thanks,
David

**Comment by ruslanskorb** [comment]
https://github.com/ruslanskorb/RSKImageCropper/issues/52

**Comment by ruslanskorb** [comment]
Won't fix. Please see my explanation [here](https://github.com/ruslanskorb/RSKImageCropper/issues/52#issuecomment-347944133).
