### ISSUE TITLE
Control buttons doesn't appear (Choose, Cancel)

### ISSUE THREAD

**Issue by pedro380085** [ruslanskorb/RSKImageCropper#110]
Hi, I've implemented this library recently and it works fine on my device.

But a user sent a video demonstrating that none of the control buttons appear, someone has a clue of what it might be?

![screen shot 2016-08-04 at 18 29 03](https://cloud.githubusercontent.com/assets/1212753/17418935/5c2f7302-5a71-11e6-86d9-d82ed8f83c69.png)

**Comment by pedro380085** [comment]
@ruslanskorb Do you know what it might be?

**Comment by ruslanskorb** [comment]
@pedro380085 Hi Pedro! First of all, I can suggest you to check your implementation of `updateViewConstraints` method.

**Comment by ruslanskorb** [comment]
@pedro380085 The problem still exists?

**Comment by pedro380085** [comment]
I've not been able to solve it yet, I believe this user had some accessibility tools enabled, such as dynamic text and zoom out.

**Comment by ruslanskorb** [comment]
@pedro380085 If you can share a part of your code that configures `RSKImageCropViewController` I can try to help you. Email me at ruslan.skorb@gmail.com
