### ISSUE TITLE
How to use this library with Swift ?

### ISSUE THREAD

**Issue by amineghabi** [ruslanskorb/RSKImageCropper#120]

**Comment by ruslanskorb** [comment]
[RSKImageCropperWithSwiftAndCocoapods](https://dl.dropboxusercontent.com/u/89891480/RSKImageCropperWithSwiftAndCocoapods.zip)
[RSKImageCropperWithSwiftCocoapodsAndModules](https://dl.dropboxusercontent.com/u/89891480/RSKImageCropperWithSwiftCocoapodsAndModules.zip)

**Comment by abellee** [comment]
@ruslanskorb then how to use?

**Comment by benoistmartins** [comment]
Hey,
The link below went to 404 error, can you please provide it back again ? :)
Thanks

**Comment by ruslanskorb** [comment]
@benoistmartins Done! :-]
