### ISSUE TITLE
Undefined symbols for architecture armv7:   "_OBJC_CLASS_$_RSKImageCropViewController", referenced from: objc-class-ref in DetailsViewController.o

### ISSUE THREAD

**Issue by sumitmagdum** [ruslanskorb/RSKImageCropper#122]

**Comment by ruslanskorb** [comment]
@sumitmagdum Can you provide more information about your problem?

**Comment by ruslanskorb** [comment]
I guess that the problem in your project settings - http://stackoverflow.com/a/6429568/2134682.

Will close the issue for now. If the problem is not related to your project configuration feel free to reopen it.
