### ISSUE TITLE
Possible to get a white background?

### ISSUE THREAD

**Issue by PieterLimburg** [ruslanskorb/RSKImageCropper#125]
Hi Ruslan,

Thanks for creating this great library! Is it possible to change the background color from black to white? Currently I'm using the circle crop method and would love to have the background to be white.

Thanks again,

Pieter

**Comment by ruslanskorb** [comment]
Hi Pieter,

You can change the background color just before presenting `RSKImageCropViewController`.

```swift
imageCropViewController.view.backgroundColor = UIColor.white
self.navigationController?.pushViewController(imageCropViewController, animated: true)
```

Or you can create a subclass of `RSKImageCropViewController` and override the method `viewDidLoad`.

```swift
override func viewDidLoad() {
        
        super.viewDidLoad()
        
        self.view.backgroundColor = UIColor.white
}
```

Cheers,
Ruslan

**Comment by PieterLimburg** [comment]
Hi Ruslan,

Thank you so much for the response. I'm actually trying to change the
background color of the cropped jpg to white. I'm using the circle crop
function which leaves a black square around the circle. After that I'm
processing the jpg and need the background to be white.

Is that at all possible?

Thanks again for your advice.

Best,

Pieter

**Comment by ruslanskorb** [comment]
You can set the value of the property `applyMaskToCroppedImage` of `RSKImageCropViewController` to `true` and redraw the cropped image with the white background.

**Comment by PieterLimburg** [comment]
Thanks again. I had already found the "appyMaskToCroppedImage" and set it
to true. But don't know how to redraw the cropped image with the white
background (currently it's black). Could really appreciate your help!

2016-12-08 12:17 GMT-05:00 Ruslan Skorb <notifications@github.com>:

**Comment by ruslanskorb** [comment]
I can recommend you to read [this](https://developer.apple.com/library/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/HandlingImages/Images.html) guideline. It should help you.

Cheers,
Ruslan
