### ISSUE TITLE
Not Able to retrieve file path

### ISSUE THREAD

**Issue by dlipiz** [ruslanskorb/RSKImageCropper#131]
Hey, Im using your library in a project that I'm working on and I need to get the full file path for the image. I noticed that the native UIImagePicker has a del method called FinishedPickingMedia that passes in a Dictionary, and in doing so am able to get the value for key. Is there any such delegate method in your lib? If so, would you mind adding this feature as its extremely when trying to save an image as a stream.
Thanks.

**Comment by ruslanskorb** [comment]
Hi @dlipiz!

**RSKImageCropper** does not save the cropped image to the disk. So there is no a file path for it. The library returns `UIImage` object that can be converted to `NSData` using ` UIImagePNGRepresentation` function and saved to the disk using `writeToFile(_:atomically:)` method.

```swift
let paths = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)
let filePath = "\(paths.first)/ImageName.png"

UIImagePNGRepresentation(image)?.writeToFile(filePath, atomically: true)
```
