### ISSUE TITLE
How to a add rectangular crop for image

### ISSUE THREAD

**Issue by perlasivakrishna** [ruslanskorb/RSKImageCropper#132]
I would like to add rectangular crop for some images and circular for some images, So I implemented data source methods. 

"imageCropViewControllerCustomMovementRect" in this method I'm passing mask size.
            maskSize = CGSize(width: 270, height: 180)
but in "imageCropViewControllerCustomMaskPath" method controller's maskrect is coming as zero's 

Could u please help me How to achieve rectangular crop ?

**Comment by ruslanskorb** [comment]
Hi @perlasivakrishna,

You should return a custom `maskRect` from the method `imageCropViewControllerCustomMaskRect(_:)`.

```swift
internal func imageCropViewControllerCustomMaskRect(_ controller: RSKImageCropViewController) -> CGRect {
    
    let viewSize = controller.view.bounds.size
    
    let maskSize = CGSize(width: 270, height: 180)
    let maskOrigin = CGPoint(x: viewSize.width / 2 - maskSize.width / 2, y: viewSize.height / 2 - maskSize.height / 2)
    
    return CGRect(origin: maskOrigin, size: maskSize)
}
    
internal func imageCropViewControllerCustomMaskPath(_ controller: RSKImageCropViewController!) -> UIBezierPath! {
    
    return UIBezierPath(rect: controller.maskRect)
}

internal func imageCropViewControllerCustomMovementRect(_ controller: RSKImageCropViewController) -> CGRect {
    
    return controller.maskRect
}
```

**Comment by perlasivakrishna** [comment]
Thanks for the reply, I did the same, But In this "imageCropViewControllerCustomMaskPath" method I'm getting mask rect as (0,0) even though I passed the maskrect in above delegate method, Any Im able to do it copying same in mask path method also for time being. 
Thanks

**Comment by ruslanskorb** [comment]
@perlasivakrishna Did you set the value of the `dataSource` property?

**Comment by perlasivakrishna** [comment]
func PresentImageCropper(image:UIImage)
    {
       let cropcontroller:RSKImageCropViewController = RSKImageCropViewController(image: image)
        cropcontroller.cropMode = .custom
        cropcontroller.dataSource = self
        cropcontroller.delegate = self
        self.navigationController?.pushViewController(cropcontroller, animated: true)
    }
Here is how I loading Image Cropper

**Comment by ruslanskorb** [comment]
The initialization looks correct. Can you provide a test project with your problem?

**Comment by perlasivakrishna** [comment]
Data Source Methods:
  func rectforcontroller(_ controller: RSKImageCropViewController) ->CGRect
    {
        
        var maskSize:CGSize
        
        if (controller.isPortraitInterfaceOrientation()) {
            maskSize = CGSize(width: 270, height: 180)
            
        } else {
            maskSize = CGSize(width: 220, height: 220)
        }
        
        let viewWidth = controller.view.frame.width
        let viewHeight = controller.view.frame.height
        
        let maskRect = CGRect(x: (viewWidth - maskSize.width) * 0.5, y: (viewHeight - maskSize.height) * 0.5, width: maskSize.width, height: maskSize.height)
        
        return maskRect;
        
    }
    func imageCropViewControllerCustomMovementRect(_ controller: RSKImageCropViewController) -> CGRect {
        
               return self.rectforcontroller(controller);
    }
    func imageCropViewControllerCustomMaskPath(_ controller: RSKImageCropViewController) -> UIBezierPath {
    
   //  Here is the problem. If Im using controller.maskrect to create mask. because controller.maskrect value is 0,0 in this method. So I took a common method to get out of this issue.  

        let  rect = self.rectforcontroller(controller);
        
        let path = UIBezierPath(rect:rect)
        
        return path
    }
    func imageCropViewControllerCustomMaskRect(_ controller: RSKImageCropViewController) -> CGRect {
       return controller.maskRect
    }

**Comment by ruslanskorb** [comment]
As I mentioned above you must return a custom `maskRect` from the method `imageCropViewControllerCustomMaskRect(_:)`. But, now, you are returning `controller.maskRect` (that is `zero` by default) instead of calculated `maskRect`.

**Comment by perlasivakrishna** [comment]
func imageCropViewControllerCustomMaskRect(_ controller: RSKImageCropViewController) -> CGRect {
   return self.rectforcontroller(controller)
}
Is this the way I have do ?

**Comment by ruslanskorb** [comment]
Yes.
