### ISSUE TITLE
imageCropViewControllerCustomMaskRect not called

### ISSUE THREAD

**Issue by chings228** [ruslanskorb/RSKImageCropper#134]
Hi , 

i init the controller as follows:  

  RSKImageCropViewController *imageCropVC = [[RSKImageCropViewController alloc] initWithImage:image cropMode:RSKImageCropModeCustom];
imageCropVC.datasource = self

but i found it only calls imageCropViewControllerCustomMaskPath   and never calls imageCropViewControllerCustomMaskRect

anything i 'm missing during the initialization , thanks

**Comment by ruslanskorb** [comment]
Hi @chings228,

Can you show your implementation of the data source methods?

**Comment by ruslanskorb** [comment]
@chings228 I'll close the issue for now. Feel free to reopen it if the problem persists.
