### ISSUE TITLE
Error: Argument Labels '(_: RSKImageCropMode:)' do not match any available overloads

### ISSUE THREAD

**Issue by pravishanth** [ruslanskorb/RSKImageCropper#137]
Hi,
Could someone please advice how I could resolve this error ? I'm trying to use this library in my swift code.

![rskimagecroppererror](https://cloud.githubusercontent.com/assets/5144335/23055543/72ad402e-f50c-11e6-8409-47312d831a75.jpeg)

**Comment by ruslanskorb** [comment]
```swift
let imageCropViewController = RSKImageCropViewController(image: photo, cropMode: .circle)
```
