### ISSUE TITLE
The moveAndScale label is not fully constrained or have the ability to wrap text.

### ISSUE THREAD

**Issue by RamiAbouGhanem** [ruslanskorb/RSKImageCropper#138]
The `moveAndScaleLabel` that is added to the `RSKImageCropViewController` only has a top and center constraint. It should also be constrained on its leading and trailing so that text can not run off the screen.

Also support for multiple lines of text would be beneficial.

**Comment by ruslanskorb** [comment]
@RamiAbouGhanem Thanks for suggestion!

There is no need to add leading and trailing constraints at the moment. The default text of `moveAndScaleLabel` is perfectly placed in all available screens.

If you need to replace it with something else I can suggest you to create a subclass of `RSKImageCropViewController`, override the method `updateViewConstraints` and add necessary constraints. It will also allow you to use multi-line text.
