### ISSUE TITLE
RSKImageCropper/CGGeometry+RSKImageCropper.h file not found

### ISSUE THREAD

**Issue by Montrazul** [ruslanskorb/RSKImageCropper#142]
I included RSKImageCropper using pod without any version.

`pod 'RSKImageCropper'`

since the error only occured since the last repo update I changed it to:

`pod 'RSKImageCropper', '~> 1.5.2'`

But still..... when I want to build my project the build fails with the error:

`RSKImageCropper/CGGeometry+RSKImageCropper.h file not found`

In The RSKImageCropper.h file.

**Comment by ruslanskorb** [comment]
Please try `pod deintegrate` and `pod install` and tell me whether the problem is resolved.
