### ISSUE TITLE
How to adjust Circle as per Image

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [ruslanskorb/RSKImageCropper#143]
Hi,

I am having issue while using library.I have selected the default image in simulator but circle is not proper shown as it seems that it does not adjust automatically.Please let me know what needs to do to show the circle inside the image.Please refer attached screenshot.

Thanks,
Rahul Gupta
![simulator screen shot 28-feb-2017 4 10 03 pm](https://cloud.githubusercontent.com/assets/5418776/23402201/93ad399c-fdd0-11e6-8409-d8c65fab9de1.png)

**Comment by ruslanskorb** [comment]
Hi @Rahulgupta-cdnsol,

Just set the value of `avoidEmptySpaceAroundImage` property  to `true`.
