### ISSUE TITLE
Customize RSKImageCropViewController Interface

### ISSUE THREAD

**Issue by jacks8x** [ruslanskorb/RSKImageCropper#144]
moveAndScaleLabel, cancelButton, chooseButton is readonly, how can I customize them, how can I hide them and add my own Button and Label
Thanks for your support!

**Comment by ruslanskorb** [comment]
To hide `moveAndScaleLabel`, `cancelButton` and `chooseButton` you need to set their property `isHidden` to `true`.
To add your own buttons and labels you need to create them and add to the view like any other usual views using the method `addSubview` of `UIView`.
