### ISSUE TITLE
Error on Xcode 8.3 Swift 3.1

### ISSUE THREAD

**Issue by khuong291** [ruslanskorb/RSKImageCropper#145]
I get this error when update to Xcode 8.3.

![screen shot 2017-03-28 at 3 59 24 pm](https://cloud.githubusercontent.com/assets/11523438/24397173/a92a3bde-13cf-11e7-89cb-8c0996c9ed7b.png)

**Comment by ruslanskorb** [comment]
What version of `RSKImageCropper` do you use?

**Comment by khuong291** [comment]
@ruslanskorb I use version 1.6.0

**Comment by ruslanskorb** [comment]
It is fixed in the version [1.6.1](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/1.6.1).

**Comment by khuong291** [comment]
Thank you 👍
