### ISSUE TITLE
Redefinition of module 'RSKImageCropper'

### ISSUE THREAD

**Issue by MonFig** [ruslanskorb/RSKImageCropper#146]
```
RSKImageCropper/RSKImageCropper/module.modulemap:1:18: Redefinition of module 'RSKImageCropper'
```

![image](https://cloud.githubusercontent.com/assets/16597492/24476284/4bc594a2-1505-11e7-9086-9d8bd073ce2a.png)

I have updated the latest version of the `RSKImageCropper`, which is 1.6.1, but the problem remains.

```
Using QBImagePickerController (3.4.0)
Using RSKImageCropper (1.6.1)
```

**Comment by dimmdesign** [comment]
@MonFig — Removing the pod and reinstalling it worked for me.

**Comment by MonFig** [comment]
@dimmdesign  I tried but failed too

**Comment by MonFig** [comment]
Solved.Should update my npm package.

**Comment by cwRichardKim** [comment]
@MonFig how did you solve this? I deleted my pods file but had the same issue. it looks like you're also using react-native-image-crop-picker?

**Comment by wootwoot1234** [comment]
@MonFig what did you do to solve this issue?

**Comment by cwRichardKim** [comment]
@wootwoot1234 I updated from react-native .29 to .42 and then installed the latest version of react-native-image-cropper (which contains a fix). bug is due to new xcode and ios 10.3

**Comment by wootwoot1234** [comment]
Dang!  I don't want to upgrade my React Native....  :(

**Comment by MonFig** [comment]
@wootwoot1234 I think run `pod update` then `npm update` might help.

**Comment by wootwoot1234** [comment]
@MonFig thanks but I ended up updating to react native 0.42 which I've been working on now for 2 days.  :(  I think I'm almost there.
