### ISSUE TITLE
Crop without use the viewController

### ISSUE THREAD

**Issue by FrankTravieso1** [ruslanskorb/RSKImageCropper#149]
Hi,

How can I crop an image using a custom mask path without showing the view controller?
I'm using Swift 3.0

If you could help me as fast as possible i would be very grateful. I'm in full development of a project.

Thanks.

**Comment by ruslanskorb** [comment]
Hi @FrankTravieso1,

RSKImageCropper does not provide this functionality.

But, maybe, [this method](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.m#L858) will help you understand how to achieve your goal.

Cheers!

**Comment by FrankTravieso1** [comment]
really thank you, I will try to code that method in swift

**Comment by FrankTravieso1** [comment]
It works to me, thank you from the depth of my heart
