### ISSUE TITLE
Issue with Xcode 8.3.2 and Cocoapods

### ISSUE THREAD

**Issue by ISCHI** [ruslanskorb/RSKImageCropper#155]
Since I switched to Xcode 8.3.2, I get an error as soon as I use this lib with CocoaPods.

Xcode shows:
`Lexical or Preprocessor Issue Group
.../Pods/RSKImageCropper/RSKImageCropper/module.modulemap:1:18: Redefinition of module 'RSKImageCropper'`

Fix: I renamed the module map file "module.modulemap" to "RSKImageCropper.modulemap".

**Comment by ruslanskorb** [comment]
This is fixed in the latest [release](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/1.6.1).

**Comment by ISCHI** [comment]
Thanks! I forgot to update Cocoapods ... :)
