### ISSUE TITLE
[Feature]Why not add functionality of image picker

### ISSUE THREAD

**Issue by CosmicYogi** [ruslanskorb/RSKImageCropper#157]
What if we can build a feature to also use it as a **UIImagePickerController**.
When a developer uses UIImagePickerController for taking image from gallery then he don't have any choice for cropping the image like what if we want only rectangular images.
This functionality can be added to this project so it would become like-
**Image Cropper + Image Picker** 
could be used in both the ways.

I can try working on it.

**Comment by ruslanskorb** [comment]
There is no need to do it.
You can present `RSKImageCropViewController` after picking an image from `func imagePickerController(_, didFinishPickingMediaWithInfo:)` method of `UIImagePickerControllerDelegate`.
