### ISSUE TITLE
rewrite this lib by using Swift3.0

### ISSUE THREAD

**Issue by LQQZYY** [ruslanskorb/RSKImageCropper#159]
Hi,
I'll rewrite this lib by using Swift 3.0, and my link is [LDPhotoCropper](https://github.com/LQQZYY/LDPhotoCropper).

According to your ideas, and change some methods to meet my needs.

If there is infringement, please contact me, and i'll delete it

Thanks

**Comment by ruslanskorb** [comment]
**RSKImageCropper** is is available under the [MIT license](https://github.com/ruslanskorb/RSKImageCropper/blob/master/LICENSE). So, all you need is to meet its conditions.

**Comment by LQQZYY** [comment]
OK，thank you for reply me first! 
I already add the MIT lience .And I rewrite this lib,just want to use it in swift objects,what's more I can all right learn it.
Thinks very much

**Comment by ruslanskorb** [comment]
@LQQZYY You can also [use **RSKImageCropper** in Swift](https://github.com/ruslanskorb/RSKImageCropper/issues/120) projects. Like any other Swift library.

**Comment by LQQZYY** [comment]
Yes,this can be used in swift.
So,I will use the original lib you writed!
And the lib l rewrited, I'll delete it later.
Thinks all the same!
