### ISSUE TITLE
RSKImageCropModeCircle not work!

### ISSUE THREAD

**Issue by shenguanjiejie** [ruslanskorb/RSKImageCropper#163]
![simulator screen shot 2017 6 14 6 38 45](https://user-images.githubusercontent.com/9425605/27128389-de25f6c2-5130-11e7-9898-2bf852d49a6b.png)
![wx20170614-183940](https://user-images.githubusercontent.com/9425605/27128396-e205031e-5130-11e7-826a-c021a0f15dc3.png)

The croped image not round but square..why?

**Comment by ruslanskorb** [comment]
You need to set `applyMaskToCroppedImage` to `true`.

**Comment by shenguanjiejie** [comment]
Perfect! Thanks! 👍
