### ISSUE TITLE
XCode-Error: "Repair target Build RSKImageCropper: invalid Team-ID"

### ISSUE THREAD

**Issue by itinance** [ruslanskorb/RSKImageCropper#164]
On Both RSKImageCropper and QBImagePicker it is not possible anymore to create an Archive. We used this library in our project for many weeks and were always able to push releases to Testflight, but since some days the following error occur:

> No "iOS Development" signing certificate matching team ID "5WFBC66J2G" with a private key was found.

Building in Release-Mode works fine. Creating an Archive ands with this error.

The interesting part is, that out Team-ID is different. So I did a grep for this Team-ID that was mentioned in the error message and encountered that it is used in RSKImageCropper and QBImagePicker.

```
$ grep -HR "5WFBC66J2G" *
node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj:						DevelopmentTeam = 5WFBC66J2G;
node_modules/react-native-image-crop-picker/ios/RSKImageCropper/RSKImageCropper.xcodeproj/project.pbxproj:						DevelopmentTeam = 5WFBC66J2G;

```

Maybe latest XCode-Updates to 8.3.3 handle those cases now different than before.

Has anyone else experienced this issue?

I already did a "clean" and rebuild each target multiple times. I deselected our Team and put it back and so on...

Any ideas?

**Comment by ruslanskorb** [comment]
You need to ask @ivpusic to remove **DevelopmentTeam** from [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker/search?utf8=✓&q=5WFBC66J2G&type=).

**Comment by itinance** [comment]
Thank you very much for your help so quickly, @ruslanskorb!
