### ISSUE TITLE
`RSKImageCropViewControllerDataSource` methods explanation

### ISSUE THREAD

**Issue by LQQZYY** [ruslanskorb/RSKImageCropper#165]
When I use the custom CropMode , and use the dataSource method like this:
```
func imageCropViewControllerCustomMaskRect(_ controller: RSKImageCropViewController) -> CGRect {
        return maskRect
    }
    func imageCropViewControllerCustomMaskPath(_ controller: RSKImageCropViewController) -> UIBezierPath {  
        return UIBezierPath(rect: maskRect)
    }
```

and , when I rotated a angle, i get a polygon result image, what i want is a rectangle image after rotated.

end I have a doubt, what the relation of the two methods? and which one can effect the crop rect ?

I have seen the result cropRect in the delegate method `imageCropViewController(_ controller: RSKImageCropViewController, didCropImage croppedImage: UIImage, usingCropRect cropRect: CGRect),` this is a rectangle, but the result image is a polygon.
last Thanks!

**Comment by ruslanskorb** [comment]
`imageCropViewControllerCustomMaskPath(_:)` returns a custom path for the mask. It defines the shape that will be rendered.
`imageCropViewControllerCustomMaskRect(_:)` returns a custom rect for the mask. It affects the crop rect.

**Comment by LQQZYY** [comment]
Thanks for reply! 
In my test, it croped two times: The first time before rotated in the cropRect, and the second time after rotated in the cropRect. For this , it will be croped to a  polygon image. What I want is that: Like the photo edit in the iPhone's photo album, it can be rotated, and croped after rotated. Please tall me what should i do to get the same effect like that?
Thinks!

**Comment by ruslanskorb** [comment]
If you want to support the rotation when `cropMode` is `RSKImageCropModeCustom` you must implement the method [`imageCropViewControllerCustomMovementRect(_:)`](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.h#L319).

I suppose that your question is related to #107. If so, you should [calculate](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.m#L689-L759) and return a valid movement rect from `imageCropViewControllerCustomMovementRect(_:)`.

**Comment by LQQZYY** [comment]
Maybe you'd better offer a demo for how to implement `imageCropViewControllerCustomMovementRect(_:)` when rotated, and how to calculate the rect for return.

Thanks!

**Comment by ruslanskorb** [comment]
A square is a special case of a rectangle. You can see how to calculate a movement rect for it [here](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.m#L689-L746). For all other cases, the movement rect is calculated individually.

**Comment by tobyhinloopen** [comment]
Did someone have a working `imageCropViewControllerCustomMovementRect` implementation yet?
