### ISSUE TITLE
Xcode 9 (beta 2) catches multiple calls to UI objects from non-main threads

### ISSUE THREAD

**Issue by dmcgloin** [ruslanskorb/RSKImageCropper#167]
When loading RSKImageCropViewController in Xcode 9 with the new: Main Thread Checker enabled (see Diagnostics in Run-Debug scheme), I receive the following issues:

Main Thread Checker: UI API called on a background thread: -[UIScrollView zoomScale]
PID: 81566, TID: 8295061, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   RSKImageCropper                     0x000000010eb52f88 -[RSKImageCropViewController cropRect] + 248
5   RSKImageCropper                     0x000000010eb5f0be __39-[RSKImageCropViewController cropImage]_block_invoke + 158
6   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf28ec _ZN6__tsanL24invoke_and_release_blockEPv + 12
7   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf2a32 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
8   libdispatch.dylib                   0x00000001132c1658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001132c66a6 _dispatch_queue_override_invoke + 1511
10  libdispatch.dylib                   0x00000001132cdd3b _dispatch_root_queue_drain + 785
11  libdispatch.dylib                   0x00000001132cd9c7 _dispatch_worker_thread4 + 54
12  libsystem_pthread.dylib             0x00000001137295a2 _pthread_wqthread + 1299
13  libsystem_pthread.dylib             0x000000011372907d start_wqthread + 13
2017-07-01 21:49:09.524874-0700 Planner[81566:8295061] [reports] Main Thread Checker: UI API called on a background thread: -[UIScrollView zoomScale]
PID: 81566, TID: 8295061, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   RSKImageCropper                     0x000000010eb52f88 -[RSKImageCropViewController cropRect] + 248
5   RSKImageCropper                     0x000000010eb5f0be __39-[RSKImageCropViewController cropImage]_block_invoke + 158
6   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf28ec _ZN6__tsanL24invoke_and_release_blockEPv + 12
7   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf2a32 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
8   libdispatch.dylib                   0x00000001132c1658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001132c66a6 _dispatch_queue_override_invoke + 1511
10  libdispatch.dylib                   0x00000001132cdd3b _dispatch_root_queue_drain + 785
11  libdispatch.dylib                   0x00000001132cd9c7 _dispatch_worker_thread4 + 54
12  libsystem_pthread.dylib             0x00000001137295a2 _pthread_wqthread + 1299
13  libsystem_pthread.dylib             0x000000011372907d start_wqthread + 13
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIScrollView contentOffset]
PID: 81566, TID: 8295061, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   RSKImageCropper                     0x000000010eb530bc -[RSKImageCropViewController cropRect] + 556
5   RSKImageCropper                     0x000000010eb5f0be __39-[RSKImageCropViewController cropImage]_block_invoke + 158
6   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf28ec _ZN6__tsanL24invoke_and_release_blockEPv + 12
7   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf2a32 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
8   libdispatch.dylib                   0x00000001132c1658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001132c66a6 _dispatch_queue_override_invoke + 1511
10  libdispatch.dylib                   0x00000001132cdd3b _dispatch_root_queue_drain + 785
11  libdispatch.dylib                   0x00000001132cd9c7 _dispatch_worker_thread4 + 54
12  libsystem_pthread.dylib             0x00000001137295a2 _pthread_wqthread + 1299
13  libsystem_pthread.dylib             0x000000011372907d start_wqthread + 13
2017-07-01 21:49:09.554868-0700 Planner[81566:8295061] [reports] Main Thread Checker: UI API called on a background thread: -[UIScrollView contentOffset]
PID: 81566, TID: 8295061, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   RSKImageCropper                     0x000000010eb530bc -[RSKImageCropViewController cropRect] + 556
5   RSKImageCropper                     0x000000010eb5f0be __39-[RSKImageCropViewController cropImage]_block_invoke + 158
6   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf28ec _ZN6__tsanL24invoke_and_release_blockEPv + 12
7   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf2a32 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
8   libdispatch.dylib                   0x00000001132c1658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001132c66a6 _dispatch_queue_override_invoke + 1511
10  libdispatch.dylib                   0x00000001132cdd3b _dispatch_root_queue_drain + 785
11  libdispatch.dylib                   0x00000001132cd9c7 _dispatch_worker_thread4 + 54
12  libsystem_pthread.dylib             0x00000001137295a2 _pthread_wqthread + 1299
13  libsystem_pthread.dylib             0x000000011372907d start_wqthread + 13
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 81566, TID: 8295061, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   RSKImageCropper                     0x000000010eb5350b -[RSKImageCropViewController cropRect] + 1659
5   RSKImageCropper                     0x000000010eb5f0be __39-[RSKImageCropViewController cropImage]_block_invoke + 158
6   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf28ec _ZN6__tsanL24invoke_and_release_blockEPv + 12
7   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf2a32 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
8   libdispatch.dylib                   0x00000001132c1658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001132c66a6 _dispatch_queue_override_invoke + 1511
10  libdispatch.dylib                   0x00000001132cdd3b _dispatch_root_queue_drain + 785
11  libdispatch.dylib                   0x00000001132cd9c7 _dispatch_worker_thread4 + 54
12  libsystem_pthread.dylib             0x00000001137295a2 _pthread_wqthread + 1299
13  libsystem_pthread.dylib             0x000000011372907d start_wqthread + 13
2017-07-01 21:49:09.576813-0700 Planner[81566:8295061] [reports] Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 81566, TID: 8295061, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   RSKImageCropper                     0x000000010eb5350b -[RSKImageCropViewController cropRect] + 1659
5   RSKImageCropper                     0x000000010eb5f0be __39-[RSKImageCropViewController cropImage]_block_invoke + 158
6   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf28ec _ZN6__tsanL24invoke_and_release_blockEPv + 12
7   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf2a32 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
8   libdispatch.dylib                   0x00000001132c1658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001132c66a6 _dispatch_queue_override_invoke + 1511
10  libdispatch.dylib                   0x00000001132cdd3b _dispatch_root_queue_drain + 785
11  libdispatch.dylib                   0x00000001132cd9c7 _dispatch_worker_thread4 + 54
12  libsystem_pthread.dylib             0x00000001137295a2 _pthread_wqthread + 1299
13  libsystem_pthread.dylib             0x000000011372907d start_wqthread + 13
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView transform]
PID: 81566, TID: 8295061, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   RSKImageCropper                     0x000000010eb54509 -[RSKImageCropViewController rotationAngle] + 185
5   RSKImageCropper                     0x000000010eb5f12f __39-[RSKImageCropViewController cropImage]_block_invoke + 271
6   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf28ec _ZN6__tsanL24invoke_and_release_blockEPv + 12
7   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf2a32 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
8   libdispatch.dylib                   0x00000001132c1658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001132c66a6 _dispatch_queue_override_invoke + 1511
10  libdispatch.dylib                   0x00000001132cdd3b _dispatch_root_queue_drain + 785
11  libdispatch.dylib                   0x00000001132cd9c7 _dispatch_worker_thread4 + 54
12  libsystem_pthread.dylib             0x00000001137295a2 _pthread_wqthread + 1299
13  libsystem_pthread.dylib             0x000000011372907d start_wqthread + 13
2017-07-01 21:49:09.596131-0700 Planner[81566:8295061] [reports] Main Thread Checker: UI API called on a background thread: -[UIView transform]
PID: 81566, TID: 8295061, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   RSKImageCropper                     0x000000010eb54509 -[RSKImageCropViewController rotationAngle] + 185
5   RSKImageCropper                     0x000000010eb5f12f __39-[RSKImageCropViewController cropImage]_block_invoke + 271
6   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf28ec _ZN6__tsanL24invoke_and_release_blockEPv + 12
7   libclang_rt.tsan_iossim_dynamic.dylib 0x000000010acf2a32 _ZN6__tsanL22dispatch_callback_wrapEPv + 306
8   libdispatch.dylib                   0x00000001132c1658 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001132c66a6 _dispatch_queue_override_invoke + 1511
10  libdispatch.dylib                   0x00000001132cdd3b _dispatch_root_queue_drain + 785
11  libdispatch.dylib                   0x00000001132cd9c7 _dispatch_worker_thread4 + 54
12  libsystem_pthread.dylib             0x00000001137295a2 _pthread_wqthread + 1299
13  libsystem_pthread.dylib             0x000000011372907d start_wqthread + 13

**Comment by ruslanskorb** [comment]
@dmcgloin Thanks for reporting! Fixed in [1.6.3](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/1.6.3) 🎉

**Comment by dmcgloin** [comment]
@ruslanskorb Nice! Confirmed fix in 1.6.3.

Now if only Google could fix same issue in their stuff as quick as you :)
