### ISSUE TITLE
can't get corrected image

### ISSUE THREAD

**Issue by shilihuan** [ruslanskorb/RSKImageCropper#168]
when i push to RSKImageCropViewController, it always log "[Generic] Creating an image format with an unknown type is an error" in DEBUG area,  then i can't get correct image in delegate of "imageCropViewController:(RSKImageCropViewController *)controller didCropImage:(UIImage *)croppedImage usingCropRect:(CGRect)cropRect "

**Comment by ruslanskorb** [comment]
Probably, you are getting an incorrect image from `UIImagePickerController`. Please see #150.

**Comment by shilihuan** [comment]
i set the cropRect is (128, 128), CustomMode, but in the return croppedImage delegate method, the image not is (128, 128), why?
