### ISSUE TITLE
the croppedImage size is not my size which i have set cropRect

### ISSUE THREAD

**Issue by shilihuan** [ruslanskorb/RSKImageCropper#169]
i set the cropRect is (128, 128), CustomMode, but in the return croppedImage delegate method, the image not is (128, 128), why? it is much bigger than cropRect，- (void)imageCropViewController:(RSKImageCropViewController *)controller didCropImage:(UIImage *)croppedImage usingCropRect:(CGRect)cropRect` the cropRect is not my cropRect

**Comment by ruslanskorb** [comment]
In custom mode you are providing `maskRect`. `cropRect` is calculated at run time [based on parameters of underlying `imageScrollView`](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.m#L388-L414).

**Comment by shilihuan** [comment]
the maskSize which i provide  in datasource method is (128, 128), i don't understand why the image size is not equal to maskSize
