### ISSUE TITLE
How can I force French as a language?

### ISSUE THREAD

**Issue by Ouadie** [ruslanskorb/RSKImageCropper#173]

**Comment by ruslanskorb** [comment]
You need to get access to the proper translations bundle, query that bundle for the translations and manually update the text in 'Cancel' and 'Choose' buttons and 'Move and Scale' label.

[This link](https://stackoverflow.com/questions/27879232/force-nslocalizedstring-to-use-a-specific-language-using-swift) can be useful to you.
