### ISSUE TITLE
Black image issue.

### ISSUE THREAD

**Issue by MehulSojitra16** [ruslanskorb/RSKImageCropper#175]
It return's black image if image captured using device camera.
I have tested it in iPhone6Plus, iPhone7Plus and in iPhone7.

**Comment by ruslanskorb** [comment]
I have tested `RSKImageCropper` on iPhone 7 right now and everything is OK. Please, check your configuration.

**Comment by MehulSojitra16** [comment]
I am really sorry. 
Here is one little bit mistake from me.
Actually its working fine in RSKImageCropper. but issue is in swift library(RSKImageCropperSwift).
