### ISSUE TITLE
Include of non-modular header inside framework module errors

### ISSUE THREAD

**Issue by DarkByte3PG** [ruslanskorb/RSKImageCropper#177]
Hello, I'm encountering these errors on Xcode 9 with Swift 4, RSKImageCropper v1.6.3 (I've even tried with 1.6.0, 1.6.1, 1.6.2)

![screen shot 2017-10-13 at 11 36 20](https://user-images.githubusercontent.com/16716552/31537429-c94587f2-b00a-11e7-98fb-31032133928a.png)

My CocoaPods version is 1.3.1 and the "allow include non-modular" flag doesn't do anything for me.

If you need more information, please let me know. I'm stuck with this issue.

Thanks!

**Comment by ruslanskorb** [comment]
Hi @DarkByte3PG,

Try deintegrate and install **RSKImageCropper** again and let me know if the problem still persists.

**Comment by DarkByte3PG** [comment]
It seems my Xcode installation had some issues, probably introduced by myself. I've reverted a couple of commits (after digging everything and everywhere), took it from there and now it's working fine.

Sorry for the mess! :)

**Comment by vkolosovsky** [comment]
@ruslanskorb I see exactly same build error (Xcode 10.3, Swift 4.2)
<img width="722" alt="Screen Shot 2019-08-12 at 18 18 40" src="https://user-images.githubusercontent.com/10945964/62876444-a3280e00-bd2d-11e9-9dd4-dbfae1bafb6a.png">

**Comment by vkolosovsky** [comment]
Same problem on Xcode 11.2
