### ISSUE TITLE
Should update controls' layout for iphone X

### ISSUE THREAD

**Issue by Annabelle1024** [ruslanskorb/RSKImageCropper#178]
When using iphone X, the buttons' and circleMask's layout are not exactly right. I think you may need to update the layout.

**Comment by ruslanskorb** [comment]
Hi @Annabelle1024!

Thanks for your thoughts about **RSKImageCropper**!

I think that there is no need to update the current layout. It looks good to me and it is similar to the layout of the photo cropper from the Contacts app.

If you need to use another layout for iPhone X, I can suggest you to override the method `updateViewConstraints` and make the necessary changes.
