### ISSUE TITLE
Image not moving in vertical mode after rotate.

### ISSUE THREAD

**Issue by dineshmahajan** [ruslanskorb/RSKImageCropper#179]
When I rotate image with 90 degree then not able to move image top & down, please check & let me know solution for it.

**Comment by ruslanskorb** [comment]
@dineshmahajan Can you provide a sample project?

**Comment by dineshmahajan** [comment]
Please check attach video file Frame is not updates after rotate
[Video.zip](https://github.com/ruslanskorb/RSKImageCropper/files/1443247/Video.zip)

**Comment by ruslanskorb** [comment]
@dineshmahajan I noticed that you are using a custom crop mode.
Can you, please, provide your implementation of `RSKImageCropViewControllerDataSource` methods?

**Comment by dineshmahajan** [comment]
[Class.zip](https://github.com/ruslanskorb/RSKImageCropper/files/1443791/Class.zip)
Hi Thanks for quick response, Please download my file & replace RSKExampleViewController class in an example provided on git.

Thanks

**Comment by ruslanskorb** [comment]
@dineshmahajan 

If you want to support the rotation  when `cropMode` is `RSKImageCropModeCustom` you must implement the method [`imageCropViewControllerCustomMovementRect:`](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.h#L319).

If the image is not rotated, then the movement rect coincides with the mask rect. In other cases you need to calculate and return the correct value from `imageCropViewControllerCustomMovementRect:`.

You can see how it is done for the square [here](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.m#L689-L746).

**Comment by dineshmahajan** [comment]
If i need to do calculation at my end. Then what is the use library in case
of custom crop. It should be managed by library. Please let me know if you
can provide me solution otherwise i will use other library.

**Comment by ruslanskorb** [comment]
It is impossible to calculate a movement rect for an unknown mask rect. Therefore, it is the responsibility of the developer who uses this library.

**Comment by dineshmahajan** [comment]
Can you please provide me example code where you implemented custom crop
functionality. So i can test and implement accordingly.

**Comment by ruslanskorb** [comment]
You can see how to calculate a movement rect for the square [here](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageCropViewController.m#L689-L746). I hope it will guide you in the right direction.

**Comment by dineshmahajan** [comment]
I want to implement same like twitter. It will be great if you can send me with custom . Because in case of square it's easy to manage height and width. I need to implement this today.

**Comment by iPhoNewsRO** [comment]
@ruslanskorb i also needed this implementation so maybe you can add the following code i used in the readme file:

add this to your Utils class or VC
```
func getBoundingRectAfterRotation(rect: CGRect, angle: Float) -> CGRect {
        let newWidth : Float = Float(rect.size.width) * abs(cosf(angle)) + Float(rect.size.height) * fabs(sinf(angle))
        
        let newHeight : Float = Float(rect.size.height) * fabs(cosf(angle)) + Float(rect.size.width) * fabs(sinf(angle))
        
        let newX : Float = Float(rect.origin.x) + ((Float(rect.size.width) - newWidth) / 2);
        let newY : Float = Float(rect.origin.y) + ((Float(rect.size.height) - newHeight) / 2);
        let rotatedRect = CGRect(x: CGFloat(newX), y: CGFloat(newY), width: CGFloat(newWidth), height: CGFloat(newHeight))
        
        return rotatedRect
    }
```

then implement **RSKImageCropViewControllerDataSource** and add:

`func imageCropViewControllerCustomMovementRect(_ controller: RSKImageCropViewController) -> CGRect {
        return self.getBoundingRectAfterRotation(rect: controller.maskRect, angle: Float(controller.rotationAngle))
    }`

thank you for this great library!

**Comment by ruslanskorb** [comment]
Added working example to README.
