### ISSUE TITLE
Reuse RSKImageCropViewController object

### ISSUE THREAD

**Issue by butterpuf** [ruslanskorb/RSKImageCropper#181]
I have created RSKImageCropViewController as an instance variable. For the first time I set the variable originalImage of view controller, it works fine. But the second time when I set the originalImage, it still shows me previous image. When I hit choose it crops the image I set on second time!

The only error I think is image not get updated on crop view. Should I call some function to update it?

**Comment by ruslanskorb** [comment]
You don't need to call any additional functions.

I checked your use case in the Example app and made sure that everything works well.

You can replace [this method](https://github.com/ruslanskorb/RSKImageCropper/blob/master/Example/RSKImageCropperExample/RSKExampleViewController.m#L164-L168) with the following and see that the image changes:

```objective-c
- (void)imageCropViewController:(RSKImageCropViewController *)controller didCropImage:(UIImage *)croppedImage usingCropRect:(CGRect)cropRect
{
    if (arc4random() % 2 == 0) {
        
        UIImage *photo = [UIImage imageNamed:@"photo_2"];
        controller.originalImage = photo;
    }
    else {
        
        UIImage *photo = [UIImage imageNamed:@"photo"];
        controller.originalImage = photo;
    }
}
```

Probably you are changing your image not on the main thread.

**Comment by butterpuf** [comment]
Hi, I am using UIImagePickerController to select image and use the following function to pass it to  RSKImageCropViewController. I think image picker controller calls its delegate on main thread!!.

public func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        
        activityIndicator.hide()
        imagePicker?.dismiss(animated: true, completion: nil)
        
        let image = info[UIImagePickerControllerOriginalImage] as! UIImage
        showCropper(image: image)
    }
    public func showCropper (image: UIImage) {
        
        if (cropViewController == nil) {
            cropViewController = RSKImageCropViewController()
            cropViewController!.modalTransitionStyle = .crossDissolve
            cropViewController!.delegate = self
            cropViewController!.maskLayerColor = UIColor(red: 1, green: 1, blue: 1, alpha: 0.65)
            cropViewController!.cancelButton.setTitleColor(#colorLiteral(red: 0.9633908868, green: 0.5702037811, blue: 0.1652590632, alpha: 1), for: .normal)
            cropViewController!.chooseButton.setTitleColor(#colorLiteral(red: 0.9633908868, green: 0.5702037811, blue: 0.1652590632, alpha: 1), for: .normal)
            cropViewController!.chooseButton.setTitle("Crop", for: .normal)
            cropViewController!.title = ""
        }
        cropViewController!.originalImage = image
        present(cropViewController!, animated: true, completion: completion)
    }

**Comment by ruslanskorb** [comment]
You can change `originalImage` only before the first presentation of `RSKImageCropViewController` and when `RSKImageCropViewController` is presented.
In your case you need to create a new instance of `RSKImageCropViewController` for each picked image.

**Comment by butterpuf** [comment]
ohhh. Ok great.
