### ISSUE TITLE
I set applyMaskToCroppedImage = YES,but the returned image have margins and their alpha is 0. 

### ISSUE THREAD

**Issue by shenguanjiejie** [ruslanskorb/RSKImageCropper#182]
Then I call UIImageJPEGRepresentation(image,1);  the margins will turn to whiteColor. like that
![0 _1 tiff](https://user-images.githubusercontent.com/9425605/33230136-06185f1c-d219-11e7-94ea-5b742207182d.png)

**Comment by ruslanskorb** [comment]
Sorry, but I didn't understand your problem. Please provide more information.

**Comment by shenguanjiejie** [comment]
😂  Sorry~ 
'RSKImageCropViewController *imageCropVC = [[RSKImageCropViewController alloc] initWithImage:image];
    imageCropVC.applyMaskToCroppedImage = YES;'


<img width="1933" alt="wx20171127-112800 2x" src="https://user-images.githubusercontent.com/9425605/33249579-622fc792-d366-11e7-8354-cf6c1270316a.png">


Then I call UIImageJPEGRepresentation(croppedImage,1);

result:
![img_cc1acc6b372d-1](https://user-images.githubusercontent.com/9425605/33249590-7509d43e-d366-11e7-822b-426c474c4636.jpeg)

**Comment by ruslanskorb** [comment]
Try to set `avoidEmptySpaceAroundImage` to `true`.

**Comment by shenguanjiejie** [comment]
Not work..

**Comment by ruslanskorb** [comment]
Can you, please, provide your implementation of `RSKImageCropViewControllerDataSource` methods and the image you trying to crop?

**Comment by shenguanjiejie** [comment]
![image](https://user-images.githubusercontent.com/9425605/33261062-934ffad2-d39c-11e7-8190-555d77ad66a7.png)
![image](https://user-images.githubusercontent.com/9425605/33261084-a67f30dc-d39c-11e7-9b37-bf13910c86e7.png)
![img_0805](https://user-images.githubusercontent.com/9425605/33261195-002bc1a4-d39d-11e7-81a4-0b20341c53f5.JPG)

#pragma mark - RSKImageCropViewControllerDelegate
- (CGRect)imageCropViewControllerCustomMaskRect:(RSKImageCropViewController *)controller{
    return [self getRect];
}

- (UIBezierPath *)imageCropViewControllerCustomMaskPath:(RSKImageCropViewController *)controller{
    CGRect rect = [self getRect];
    
    if (self.shouldClipToCircle) {
        return [UIBezierPath bezierPathWithArcCenter:CGRectGetCenter(rect) radius:rect.size.width / 2.0 startAngle:0 endAngle:2*M_PI clockwise:YES];
    }
    
    return [UIBezierPath bezierPathWithRect:rect];
}

- (void)imageCropViewControllerDidCancelCrop:(RSKImageCropViewController *)controller{
    [self.navigationController popViewControllerAnimated:YES];
}

-(void)imageCropViewController:(RSKImageCropViewController *)controller willCropImage:(UIImage *)originalImage{
//        int controllerCount = (int)self.navigationController.viewControllers.count;
//        [self.navigationController popToViewController:self.navigationController.viewControllers[controllerCount - 3] animated:YES];
}

- (void)imageCropViewController:(RSKImageCropViewController *)controller didCropImage:(UIImage *)croppedImage usingCropRect:(CGRect)cropRect{
    if (_imagesCompletion) {
        _imagesCompletion([NSArray arrayWithObject:croppedImage]);
    }
    [self.navigationController setNavigationBarHidden:NO animated:NO];
    int controllerCount = (int)self.navigationController.viewControllers.count;
    [self.navigationController popToViewController:self.navigationController.viewControllers[controllerCount - 3] animated:YES];
    
}

#pragma mark 辅助方法

- (CGRect)getRect{
    //
    if (self.imageSize.width == 0 || self.imageSize.height == 0) {
        self.imageSize = CGSizeMake(kScreenWidth, kScreenWidth);
    }
    
    CGFloat scale = MIN(kScreenWidth / self.imageSize.width, kScreenHeight / self.imageSize.height);
    CGSize scaleSize = CGSizeMake(scale * self.imageSize.width, scale * self.imageSize.height);
    CGRect rect = CGRectMake(self.view.centerX - scaleSize.width / 2.0, self.view.centerY - scaleSize.height / 2.0, scaleSize.width, scaleSize.height);
    return rect;
}

**Comment by ruslanskorb** [comment]
@shenguanjiejie Please provide values for `getRect` method.

**Comment by shenguanjiejie** [comment]
![image](https://user-images.githubusercontent.com/9425605/33261902-687a571e-d39f-11e7-9ed6-366f7f01f61f.png)

**Comment by ruslanskorb** [comment]
I mean `kScreenWidth`, `kScreenWidth`, `self.imageSize.width`, `self.view.centerX` , etc.

**Comment by shenguanjiejie** [comment]
kScreenWidth = [UIScreen mainScreen].bounds.size.width;
kScreenHeight = [UIScreen mainScreen].bounds.size.height;
![image](https://user-images.githubusercontent.com/9425605/33262431-316143d0-d3a1-11e7-8875-961a8c90cb45.png)

**Comment by ruslanskorb** [comment]
I just checked the code and the image you provided and I can say that everything should work as you need if you set the value of `avoidEmptySpaceAroundImage` to `YES`.

**Comment by shenguanjiejie** [comment]
did you zoom the image? have a try.

**Comment by ruslanskorb** [comment]
Yes, I did. Everything works properly.

![simulator screen shot - iphone 7 - 2017-11-27 at 21 14 57](https://user-images.githubusercontent.com/1182823/33284517-0d94d446-d3b8-11e7-81e4-63657b81e443.png)

<img width="600" alt="screen shot 2017-11-27 at 21 15 28" src="https://user-images.githubusercontent.com/1182823/33284546-20749aa6-d3b8-11e7-809f-cf4ffdda5724.png">

**Comment by shenguanjiejie** [comment]
Sorry about my bad English... You may not understand me. Here is my question with a demo.
https://github.com/shenguanjiejie/RJImagePicker

**Comment by ruslanskorb** [comment]
What problem do you see in these images?

![simulator screen shot - iphone x - 2017-11-28 at 10 40 24](https://user-images.githubusercontent.com/1182823/33309943-a3c7462c-d428-11e7-844c-c841c99d7219.png)
<img width="552" alt="screen shot 2017-11-28 at 10 43 33" src="https://user-images.githubusercontent.com/1182823/33310074-0d00a7a0-d429-11e7-9977-3295d6fb6e65.png">
![simulator screen shot - iphone x - 2017-11-28 at 10 40 35](https://user-images.githubusercontent.com/1182823/33309944-a3ecd5f4-d428-11e7-879e-7b3c48fc51aa.png)

**Comment by shenguanjiejie** [comment]
😭😭😭  their 
![image](https://user-images.githubusercontent.com/9425605/33312709-94f24cec-d463-11e7-8421-ac62a89a9860.png)

![image](https://user-images.githubusercontent.com/9425605/33312516-18c556a0-d463-11e7-8406-bf8c7b4e91e6.png)

You can set applyMaskToCroppedImage = NO, will no white margins.

**Comment by ruslanskorb** [comment]
@shenguanjiejie Fixed in [develop](https://github.com/ruslanskorb/RSKImageCropper/tree/develop) branch. Please check if it works for you.

**Comment by shenguanjiejie** [comment]
Perfect! Thanks😀

**Comment by ruslanskorb** [comment]
Eventually, it is fixed in [1.6.4](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/1.6.4) 🎉
Thanks for reporting!
