### ISSUE TITLE
cropping panorama image, the result was compressed

### ISSUE THREAD

**Issue by 1jacobb1** [ruslanskorb/RSKImageCropper#185]
steps:
1. choose an image (panorama image), this image will show a black portion
![img_0040](https://user-images.githubusercontent.com/12472925/33696181-e91fe6a6-db3b-11e7-9f96-99505b7b0ef0.PNG)
2. after cropping the image result 
![img_e0041](https://user-images.githubusercontent.com/12472925/33696233-31723f3a-db3c-11e7-8590-42dc1781fadb.JPG) , it was compressed

**Comment by ruslanskorb** [comment]
@1jacobb1 Can you provide a sample project with this problem?

**Comment by 1jacobb1** [comment]
just use your current project, just add an uiimageview for the container of the cropped result.

note: you must select a panaroma image. thanks!

**Comment by ruslanskorb** [comment]
@1jacobb1 Sorry, I didn't understand you. Can you provide your panoramic image? I checked my image and everything works properly.

**Comment by 1jacobb1** [comment]
did you zoom it out?

**Comment by ruslanskorb** [comment]
yes

**Comment by 1jacobb1** [comment]
ok i will make and provide you a sample project

**Comment by ruslanskorb** [comment]
@1jacobb1 Is the issue resolved by you?

**Comment by ruslanskorb** [comment]
@1jacobb1 If the problem still persists feel free to reopen the issue.
