### ISSUE TITLE
Status Bar handling

### ISSUE THREAD

**Issue by wbsgxc** [ruslanskorb/RSKImageCropper#186]
Hi 

Thanks for the great image cropper, it is very easy to integrate, decent looking and good performance. So... thanks and well done :)

I wanna raise a minor issue regarding how the current RSKImageCropperViewController is handling the status bar.

I do see that we are manually set status bar hidden at the "viewWillAppear" stage and I also see the controller assign back the status bar hidden value back inside "viewWillDisappear". In case of an application delegates the status bar's appearance property in each view controller, e.g. a video app or a game fixed up vertical settings page with status bar with landscape full-screen mode without status bar, this will cause trouble for the whole app.

Best regards
Xiaochen

**Comment by ruslanskorb** [comment]
Hi @wbsgxc,

Thanks for reporting the issue.

Could you, please, describe in more detail the problem that arises, or provide a video / screenshot with this problem?

**Comment by wbsgxc** [comment]
Hey 

Thanks for the reply. I don have a screen shot at this moment, also better not having one as might contain confidential information of the clients…. 

Basically, I have for example, in the navigatonController:
    override var prefersStatusBarHidden: Bool {
        return (self.topViewController?.prefersStatusBarHidden)!
    }

So that each viewController’s behaviour will be reflected. However when we do (RSKImageCropViewController.m line 160)
    UIApplication *application = [UIApplication rsk_sharedApplication];
    if (application) {
        self.originalStatusBarHidden = application.statusBarHidden;
        [application setStatusBarHidden:YES];
    }

This will case the view controller’s “hidden preference” been overwritten.

Once again, thanks for great repo, well done :)

Best regards
Xiaochen

**Comment by ruslanskorb** [comment]
Hey @wbsgxc,

`RSKImageCropViewController` overrides `prefersStatusBarHidden` property. So, this shouldn't be a problem.

If you don't want to hide the status bar I can suggest you to create a subclass of `RSKImageCropViewController` and override `prefersStatusBarHidden` property to return `NO`.

**Comment by ruslanskorb** [comment]
@wbsgxc I will close the issue for now. Feel free to reopen it if you have any other suggestions regarding status bar handling.

**Comment by rmusetti81** [comment]
Sorry but create a subclass and override prefersStatusBarHidden not work.
Help please!!

**Comment by rpendleton** [comment]
Overriding prefersStatusBarHidden didn't work for me either since the viewWillAppear is setting it directly on UIApplication. Removing that method call fixed it for me though.

**Comment by wbsgxc** [comment]
@rpendleton please refer my comment above. 
1. Remove the prefersStatusBarHidden from UIApplication level
2. Propagate the property overridden down from parent towards the frontmost view controller
Like what I try to spot, this should be fixed at the framework level.
