### ISSUE TITLE
constraint aspect ratio to fill

### ISSUE THREAD

**Issue by jalleyne** [ruslanskorb/RSKImageCropper#189]
Hi @ruslanskorb , I'm wondering if there is a way to create a fill constraint with your library? I have a portrait image and im trying to crop it square, but i want to prevent users from scaling the image below the size that covers the crop area. thanks

**Comment by ruslanskorb** [comment]
Hi @jalleyne! Just set `avoidEmptySpaceAroundImage` of `RSKImageCropViewController` to `true`.

**Comment by jalleyne** [comment]
Perfect, thanks for the quick reply. awesome library!
