### ISSUE TITLE
Why I use circular cutting, return the Square image？

### ISSUE THREAD

**Issue by c1394393468** [ruslanskorb/RSKImageCropper#190]
Why I use circular cutting, return the Square image？

I use RSKImageCropModeCircle , save to Photos, but photo is Square.

**Comment by ruslanskorb** [comment]
@c1394393468 You need to set `applyMaskToCroppedImage` of `RSKImageCropViewController` to `true`.

**Comment by c1394393468** [comment]
Thank  you !
