### ISSUE TITLE
Zoom to rect

### ISSUE THREAD

**Issue by Discobanan** [ruslanskorb/RSKImageCropper#194]
Is there a way to zoom the image to a specific rect when first displaying the crop view? It would be nice to combine face detection described [here](https://www.appcoda.com/face-detection-core-image/) with the cropping functionality. We use RSKImageCropper when users upload profile pictures, and it would be nice if we could help the users crop better profile pictures.

**Comment by ruslanskorb** [comment]
Hi @Discobanan,

Currently, **RSKImageCropper** does not allow to zoom an image to a specific rect 🔍 But this is a good idea :thumbsup:
If you have a free time to implement this functionality, I'll be glad to have a look at it!

Best,
Ruslan

**Comment by ruslanskorb** [comment]
Resolved via #195.
