### ISSUE TITLE
simplify code 

### ISSUE THREAD

**Issue by zhaochengxiang** [ruslanskorb/RSKImageCropper#203]
In RSKImageCropViewController.m

when init it, orientation originalImage.

code:

(instancetype)initWithImage:(UIImage *)originalImage
{
self = [self init];
if (self) {
_originalImage = [originalImage fixOrientation];
}
return self;
}
Then remove relative code in：

(CGRect)imageRect; 
CGSize imageSize = self.originalImage.size;
    CGFloat x = CGRectGetMinX(imageRect);
    CGFloat y = CGRectGetMinY(imageRect);
    CGFloat width = CGRectGetWidth(imageRect);
    CGFloat height = CGRectGetHeight(imageRect);
    
    UIImageOrientation imageOrientation = self.originalImage.imageOrientation;
    if (imageOrientation == UIImageOrientationRight || imageOrientation == UIImageOrientationRightMirrored) {
        imageRect.origin.x = y;
        imageRect.origin.y = floor(imageSize.width - CGRectGetWidth(imageRect) - x);
        imageRect.size.width = height;
        imageRect.size.height = width;
    } else if (imageOrientation == UIImageOrientationLeft || imageOrientation == UIImageOrientationLeftMirrored) {
        imageRect.origin.x = floor(imageSize.height - CGRectGetHeight(imageRect) - y);
        imageRect.origin.y = x;
        imageRect.size.width = height;
        imageRect.size.height = width;
    } else if (imageOrientation == UIImageOrientationDown || imageOrientation == UIImageOrientationDownMirrored) {
        imageRect.origin.x = floor(imageSize.width - CGRectGetWidth(imageRect) - x);
        imageRect.origin.y = floor(imageSize.height - CGRectGetHeight(imageRect) - y);
    }

And remove
image = [image fixOrientation];

**Comment by ruslanskorb** [comment]
The method `fixOrientation` creates a new image by copying it bit by bit. This is an expensive operation that should not be performed on the main thread. In turn, `RSKImageCropViewController` is always required to be created on the main thread. Therefore, we cannot fix the orientation of the image in `initWithImage:` initializer.
