### ISSUE TITLE
Question: Can I crop rectangular image to smaller square area

### ISSUE THREAD

**Issue by zinoviev** [ruslanskorb/RSKImageCropper#204]
Hi, this is a duplicate question as https://github.com/ivpusic/react-native-image-crop-picker/issues/890 As react-native-image-crop-picker uses RSKImageCropper Maybe @ruslanskorb can help me find the answer

**Comment by ruslanskorb** [comment]
Hi @zinoviev!

Is `avoidEmptySpaceAroundImage` property of `RSKImageCropViewController` what you need?

**Comment by zinoviev** [comment]
@ruslanskorb Thanks for quick response. I've try it, but I think result wasn't square sized. Where is good chance I did something wrong and if you say it's what I looking for I will try once more, maybe without RN wrapper lib for clear experiment. Is where the way to setup background color for this case?

**Comment by ruslanskorb** [comment]
@zinoviev Try `avoidEmptySpaceAroundImage = NO` in conjunction with `applyMaskToCroppedImage = YES`.

Background color of what?

**Comment by zinoviev** [comment]
@ruslanskorb See sample at https://github.com/ivpusic/react-native-image-crop-picker/issues/890

If we shrink original reactangular image to fit in square we need to fill remaining space with some color(or no-color) In my example it is grey. I'm wondering if we can setup this color

**Comment by ruslanskorb** [comment]
@zinoviev The remaining area is transparent and there is currently no API to fill it with color.

**Comment by ruslanskorb** [comment]
@zinoviev Have you solved the issue?
