### ISSUE TITLE
version 2.1.0 broke react-native-image-crop-picker

### ISSUE THREAD

**Issue by brandonpearcy** [ruslanskorb/RSKImageCropper#208]
See https://github.com/ivpusic/react-native-image-crop-picker/issues/850 for a detailed reported. I have been able to confirm that the 2.1.0 release broke cropping while zooming on iOS. The cropRect field in the response is bogus. Since I do not use RSKImageCropper directly, can you confirm that zooming+cropping is working as expected? If so, what changed between 2.0.1 and 2.1.0 that might cause clients to break?

**Comment by ruslanskorb** [comment]
Hi @brandonpearcy,

I can confirm that zooming+cropping is working as expected in the latest version of **RSKImageCropper**.

As far as I can see [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) library has additional post image processing. Check with its author, whether it works correctly. Probably, implementation of the `RSKImageCropViewControllerDataSource` methods should also be checked.

Also, I would like to ask you to try to reproduce the problem directly in **RSKImageCropper**. If you can do this, I will be able to help.

**Comment by ruslanskorb** [comment]
@brandonpearcy Feel free to reopen the issue if you succeed in reproducing the problem in **RSKImageCropper**.

**Comment by ruslanskorb** [comment]
Fixed in [2.2.3](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/2.2.3).
