### ISSUE TITLE
Different sizes when zooming?

### ISSUE THREAD

**Issue by raulriera** [ruslanskorb/RSKImageCropper#21]
Hi, I don't know if I understand the library correctly, but if you see this example app I did with your code http://cl.ly/ZLhB you will notice that the resulting croppedImage is changing when I scale the underlaying image.

Is this correct? shouldn't the returned `croppedImage` always be in the same size?

**Comment by ruslanskorb** [comment]
Hi Raul,

Yes, it is correct. `croppedImage` should not always be in the same size. Because the size is based on a selected region of the original image.

Sincerely,
Ruslan

**Comment by raulriera** [comment]
But, did you see the video? the `croppedImage.size` is returned in the console with different values

**Comment by ruslanskorb** [comment]
When you scale the image, the selected area of the image is changing. It has a different size than the previous one. So, the size of `croppedImage` has different values.
