### ISSUE TITLE
How can we draw and extract a part of image?

### ISSUE THREAD

**Issue by tryWabbit** [ruslanskorb/RSKImageCropper#211]
Hi,
I'm really impressed by your library! I want to ask if there is a scope for selecting a part of image and extract it as an image like the given image below. We are implementing a photo application where the user can select a part of the image and that image will be added to another image. If you guys can give me a direction how to achieve this, That would be amazing.  I really appreciate your time.
Thanks

![Untitled](https://user-images.githubusercontent.com/20557360/60753267-4b3f0e80-9fed-11e9-8bae-d09cc731a8bb.png)

**Comment by ruslanskorb** [comment]
Hi @tryWabbit!

At the moment, **RSKImageCropper** does not have this functionality. 

You can try to achieve this by subclassing `RSKImageCropViewController`, setting `cropMode` to `.custom` and implementing `RSKImageCropViewControllerDataSource` methods with the logic of selecting the desired area.

Cheers!

**Comment by tryWabbit** [comment]
Hi @ruslanskorb ,
Thanks for the quick reply and the direction! I'm going to take a look at it for sure.
