### ISSUE TITLE
 Resize the image smaller within the crop area

### ISSUE THREAD

**Issue by 1jump2** [ruslanskorb/RSKImageCropper#217]
Is it possible to resize the image within the crop area, so it's smaller _than_ the crop area?

What I'm trying to accomplish is positioning an image within a canvas for t-shirt printing. 

I guess what I want is to be able to zoom out and have everything around it transparent.

**Comment by ruslanskorb** [comment]
@1jump2 Sorry, I did not understand your question. Could you rephrase it?
