### ISSUE TITLE
Issue in zoom out 

### ISSUE THREAD

**Issue by ravifullestop** [ruslanskorb/RSKImageCropper#219]
Hello 

I have tried all the way but not succeeded as it is not allowing to zoom out. Can you please help, I have attached the issue video it is not allowing to capture the girl image completely. 

[Issue.mov.zip](https://github.com/ruslanskorb/RSKImageCropper/files/4108853/Issue.mov.zip)

**Comment by ruslanskorb** [comment]
@ravifullestop This looks like you need to set `avoidEmptySpaceAroundImage` to `NO`.

**Comment by ravifullestop** [comment]
Still this not fixed with it, and there is no setting in react native for it, can you please help.

**Comment by ruslanskorb** [comment]
@ravifullestop If you are not using **RSKImageCropper** directly, please contact the owner of the react native repository with your problem.
