### ISSUE TITLE
Do you submit your code for pod?

### ISSUE THREAD

**Issue by Wangxiaotao** [ruslanskorb/RSKImageCropper#22]
when i use pod 'RSKImageCropper', and run pod install, i found that the code missing the custom UI feature?

/**
 The mode for cropping.
 */
@property (assign, nonatomic) RSKImageCropMode cropMode;

/// -------------------------------------------
/// @name Checking of the Interface Orientation
/// -------------------------------------------

/**
 Returns a Boolean value indicating whether the user interface is currently presented in a portrait orientation.
 
 @return YES if the interface orientation is portrait, otherwise returns NO.
 */
- (BOOL)isPortraitInterfaceOrientation;

@end

**Comment by ruslanskorb** [comment]
Hi @Wangxiaotao,

What do you mean?
I just checked the installation using cocoapods and everything works fine.

Sincerely,
Ruslan

**Comment by Wangxiaotao** [comment]
my podfile is like

pod 'RSKImageCropper'

after the installation, the following code is not found.
but i fix it by modifying the podfile 

pod 'RSKImageCropper', :git => 'https://github.com/ruslanskorb/RSKImageCropper.git'

and run install, the missing code come back.


/**
 The Title Label.
 */
@property (strong, nonatomic, readonly) UILabel *moveAndScaleLabel;

/**
 The Cancel Button.
 */
@property (strong, nonatomic, readonly) UIButton *cancelButton;

/**
 The Choose Button.
 */
@property (strong, nonatomic, readonly) UIButton *chooseButton;

**Comment by ruslanskorb** [comment]
RSKImageCropper is available in the repository CocoaPods - https://github.com/CocoaPods/Specs/blob/master/Specs/RSKImageCropper/0.4.0/RSKImageCropper.podspec.json.
I think you have a problem with CocoaPods that you have installed.

Cheers,
Ruslan

**Comment by yas375** [comment]
@ruslanskorb I think @Wangxiaotao is right. The latest version available via CocoaPods if 0.4.0, but but there is a pull request has been merged into master since then. And that pull request exactly contains the code @Wangxiaotao is referencing here. 

Here is the diff between `0.4.0` and `master`: https://github.com/ruslanskorb/RSKImageCropper/compare/0.4.0...master

The problem can be solved if you would tag a new version (i.e. 0.4.1) and push the new version to CocoaPods' trunk service.

**Comment by ruslanskorb** [comment]
Oh, It is my mistake...
I will make a new version and push them to CocoaPods.
@Wangxiaotao Sorry about that!
@yas375 Thanks!

**Comment by ruslanskorb** [comment]
Fixed :innocent:

**Comment by yas375** [comment]
:+1:

**Comment by Wangxiaotao** [comment]
Thank you for fixing it, nice~
