### ISSUE TITLE
How can one manipulate maskLayerColor in Swift?

### ISSUE THREAD

**Issue by vadim-inmanage** [ruslanskorb/RSKImageCropper#220]

**Comment by ruslanskorb** [comment]
@vadim-inmanage What do you mean by **manipulate**?

**Comment by vadim-inmanage** [comment]
Thanks for the quick response!
I am trying to change the partly opaque dark layer (with the opaque circle inn the middle) to white opaque layer
From what I understand, I should change the maskLayerColor to achieve this? though changing it from my view controller after initializing the RSKImageCropViewController:
`        let image = info[.originalImage] as? UIImage
        let imgCropper = RSKImageCropViewController(image: image)
        imgCropper.maskLayerColor = UIColor.white
        navigationController?.pushViewController(imgCropper, animated: true)`

Not working, also changing it directly in the SDK ( in RSKImageCropViewController file ) doesn't work.

I'm attaching a screenshot of what I am trying to achieve,
Thanks in advance
<img width="319" alt="Screen Shot 2020-02-13 at 6 11 27" src="https://user-images.githubusercontent.com/59966204/74400765-b4122300-4e27-11ea-840a-6fc63feff5dd.png">

**Comment by ruslanskorb** [comment]
`imageCropViewController.maskLayerColor = UIColor(white: 1.0, alpha: 0.5)` should work.

@vadim-inmanage Could you provide a sample project that reproduces your problem?

**Comment by vadim-inmanage** [comment]
Silly me, while making a sample project to upload I realize **I wasn't implementing  RSKImageCropViewControllerDataSource** !
Everything works now, thanks

**Comment by ruslanskorb** [comment]
@vadim-inmanage Glad to hear that everything works 👍
