### ISSUE TITLE
What is the point of method swizzling UIApplication.shared?

### ISSUE THREAD

**Issue by CapnSpellcheck** [ruslanskorb/RSKImageCropper#223]
I don't like having this swizzle in my app. What is the purpose?
Seems like the rsk_sharedApplication is only used if `respondsToSelector:@selector(prefersStatusBarHidden) == NO`. Nobody still runs or cares about iOS version that doesnt have this method.

**Comment by ruslanskorb** [comment]
The minimum supported version for **RSKImageCropper** is **iOS 6**. `prefersStatusBarHidden` property is available starting from iOS 7.0. So, we need `respondsToSelector:@selector(prefersStatusBarHidden) == NO` check.

As for the method swizzling, we need it to support extensions.
