### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by vincentthe0ne** [ruslanskorb/RSKImageCropper#225]
Hey! I would like to request, that your ImageCropper supports the Swift Package Manager. Is that possible?

**Comment by ruslanskorb** [comment]
Hi, @vincentthe0ne.

Support for SPM was added in version [2.3.0](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/2.3.0).

**Comment by vincentthe0ne** [comment]
Sorry @ruslanskorb Haven't seen that yet, thank you!
