### ISSUE TITLE
Localisation is not working

### ISSUE THREAD

**Issue by Wassmd** [ruslanskorb/RSKImageCropper#227]
I added the framework using SPM. 
"Move and Scale", Cancel, and choose are not localised

On break point:
 NSString *stringsBundlePath = [bundleForClass pathForResource:@"RSKImageCropperStrings" ofType:@"bundle"];

stringsBundlePath is nil 

<img width="1268" alt="Screen Shot 2020-12-11 at 13 01 24" src="https://user-images.githubusercontent.com/5626993/101901258-10151780-3bb1-11eb-9254-dd31f19e899f.png">

**Comment by ruslanskorb** [comment]
@Wassmd Fixed in version [3.0.1](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/3.0.1).

**Comment by Wassmd** [comment]
Thanks @ruslanskorb it works now 🥇
