### ISSUE TITLE
The position of the photo to be cropped does not change.

### ISSUE THREAD

**Issue by yakupcaglan** [ruslanskorb/RSKImageCropper#229]
I have a problem. This problem does not occur when I select photos from the Photo Library. However, when I take a photo from the camera, I do not adjust the position of the photo while cropping it. It comes back to the same position when I slide it.

https://user-images.githubusercontent.com/13396852/104616857-d77ac900-569b-11eb-925b-8ea7809ab03d.mov

Do you have an idea?

thanks in advancee  :)

**Comment by ruslanskorb** [comment]
@yakupcaglan Are you using `custom` crop mode?

**Comment by ruslanskorb** [comment]
@yakupcaglan Feel free to reopen the issue if it's not resolved.
