### ISSUE TITLE
Warning when include RSKImageCropper in SPM

### ISSUE THREAD

**Issue by Desmuz** [ruslanskorb/RSKImageCropper#230]
ignoring broken symlink /Users/*/RSKImageCropper/RSKImageCropper/include/RSKImageCropper/UIApplication+RSKImageCropper.h

When try to open this file in Xcode - file does not open.

**Comment by ruslanskorb** [comment]
@Desmuz Fixed in [3.0.2](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/3.0.2).

**Comment by Desmuz** [comment]
👍
