### ISSUE TITLE
Small and fix size cropping

### ISSUE THREAD

**Issue by sugitatestblue** [ruslanskorb/RSKImageCropper#241]
Hello

I want to use it for small square rectangle which fixed.
is it possible?

**Comment by sugitatestblue** [comment]
`avoidEmptySpaceAroundImage = true` is good
but bouncing.

**Comment by sugitatestblue** [comment]
```
alwaysBounceVertical = false
alwaysBounceHorizontal = false
```
didn't work.

**Comment by ruslanskorb** [comment]
Hey @sugitatestblue,

Sorry for the late replay. Could you check out the [develop](https://github.com/ruslanskorb/RSKImageCropper/tree/develop) branch and let me know if you can do what you wanted using the [latest additions](https://github.com/ruslanskorb/RSKImageCropper/commit/ff7fc57aa4dd60e0513347de9759df1e95825b0b)?
