### ISSUE TITLE
RSKImageCropper

### ISSUE THREAD

**Issue by Raka231** [ruslanskorb/RSKImageCropper#245]
Hey Ruslan Skorb, Could you please convert RSKImageCropper library into Swift.

**Comment by ruslanskorb** [comment]
Hey, @Raka231. Although **RSKImageCropper** is written in Objective-C, it can be used from code written in Swift. Is there really a need to rewrite it using the Swift language? Have you encountered any problems that require this?

**Comment by randarnold** [comment]
I use RSKImageCropper in a swift app with no issues that I can find.

**Comment by ruslanskorb** [comment]
@Raka231 Feel free to reopen the issue if there really is a need to rewrite **RSKImageCropper** using the **Swift** language, which we are not aware of.
