### ISSUE TITLE
Privacy manifest required by Apple

### ISSUE THREAD

**Issue by wenfeng-duan** [ruslanskorb/RSKImageCropper#250]
Hi team,

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file.
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Does this SDK need a privacy manifest? If yes, is there any plans to add a privacy manifest?

Thanks,
Duan

**Comment by ruslanskorb** [comment]
Hi, @wenfeng-duan.

**RSKImageCropper** doesn't require a privacy manifest.

Also, following [Apple's recommendations](https://developer.apple.com/forums/thread/746481?answerId=782256022#782256022), we should avoid adding an empty privacy manifest to the framework.

Cheers,
Ruslan
