### ISSUE TITLE
Rotate function

### ISSUE THREAD

**Issue by dyadenkor** [ruslanskorb/RSKImageCropper#30]
Would be great if you will add rotation feature. Thanks

**Comment by ruslanskorb** [comment]
I will try to add this feature soon.

Thanks,
Ruslan

**Comment by dyadenkor** [comment]
Wow, I wanted say thank you for your quick work, but unfortunately you have a couple mistakes.
I set  imageCropVC.avoidEmptySpaceAroundImage = YES;
so hope I can't see black space in crop area like here
https://www.dropbox.com/s/jr2qtiuturpsymq/Screenshot%202015-03-02%2000.34.15.png?dl=0,

but result surprise me more
https://www.dropbox.com/s/4s4na2pe4rqe4vj/Screenshot%202015-03-02%2000.41.39.png?dl=0

https://www.dropbox.com/s/ue01mv0kkvpgkp2/Screenshot%202015-03-02%2000.42.06.png?dl=0
https://www.dropbox.com/s/t41lmkxu79pu9ou/Screenshot%202015-03-02%2000.42.16.png?dl=0

https://www.dropbox.com/s/qyhgcb1mqxssppj/Screenshot%202015-03-02%2000.42.37.png?dl=0
https://www.dropbox.com/s/p5crw5uga2brshv/Screenshot%202015-03-02%2000.42.43.png?dl=0

Thanks

**Comment by dyadenkor** [comment]
https://www.dropbox.com/s/6096qo8cp5dmgl4/Screenshot%202015-03-02%2000.43.31.png?dl=0
https://www.dropbox.com/s/k9ptszp8bkw6x90/Screenshot%202015-03-02%2000.43.43.png?dl=0

**Comment by dyadenkor** [comment]
I need this crop feature for rectangle area and square :) For circle it looks nice. Thanks

**Comment by pronebird** [comment]
it seems that you need to scale image on rotation to avoid black bars.

**Comment by ruslanskorb** [comment]
Yes, it's my mistake. I'll fix it soon. Sorry guys!

**Comment by pronebird** [comment]
Hey, no apologies, thanks for your efforts, I wish I could help you more but I am swamped on other projects, currently maintaining couple of my own pods too, it's tough.

**Comment by ruslanskorb** [comment]
I need more time :-]

**Comment by heistings** [comment]
I'm sorry, I'm a new fish. How can you contribute code for this issue? And where did you put the commit "[RSKImageCropViewController] Add support for rotation." ?

**Comment by pronebird** [comment]
@heistings welcome! I guess this commit was stripped because I can't seem to trace it either.

**Comment by pronebird** [comment]
I'd say instead of hacking rotations through some property, we could simply implement the necessary methods to handle rotations, resize view and recalculate bounds and let to handle the rest to developer.

- `willRotateToInterfaceOrientation:duration:` for iOS < 8
- `viewWillTransitionToSize:withTransitionCoordinator:` on iOS >= 8

**Comment by heistings** [comment]
@pronebird Thanks for your passion. I think we may support a crop view instead to enable user to customize his own controller. Or we just make public property to enable user to subclass the controller.

**Comment by ruslanskorb** [comment]
Hi guys!
What do you think about this - fb30e1fc59bddd200303261a3f08ef014e054fd9?
I wish to hear your feedback :-]

**Comment by dyadenkor** [comment]
Well done!!!

**Comment by pronebird** [comment]
Nice but why do use tgmath, what's wrong with math.h itself?
