### ISSUE TITLE
Add ability to customize interface.  

### ISSUE THREAD

**Issue by dyadenkor** [ruslanskorb/RSKImageCropper#31]
Maybe it will great add image cropper as UIView inherit, not UIViewController for easy customization? Thanks

**Comment by pronebird** [comment]
What kind of customization are you looking for and what can't you achieve with view controller subclass?

**Comment by dyadenkor** [comment]
Fx, change colors and fonts for butons, remove label, change buttons position, change text to images and so on. Why they have readonly property? :)

**Comment by pronebird** [comment]
There is nothing that prevents you from doing so from view controller subclass, e.g. you can hide or reposition undesired elements and add your own stuff on top.

**Comment by ruslanskorb** [comment]
Hi @dyadenkor,

@pronebird is right. You can do it using view controller subclass.

@pronebird, thanks for your participation! :star:
