### ISSUE TITLE
Workspace Empty

### ISSUE THREAD

**Issue by rahulgupta6485** [ruslanskorb/RSKImageCropper#40]
I have downloaded the source and trying to run But as I open workspace but didn't able to compile the code... Pods are missing.What I need to run this source code.

**Comment by pronebird** [comment]
Go to Example folder and run pod install, then open workspace.

**Comment by ruslanskorb** [comment]
As @pronebird mentioned above, you have to run `pod install`.
Thanks @pronebird!
