### ISSUE TITLE
Doesn't work with 2x and 3x images

### ISSUE THREAD

**Issue by romaincointepas** [ruslanskorb/RSKImageCropper#41]
Thanks for this cool library!

In example project, in `Images.xcassets`, add an image as 2x (or 3x) for `photo`, then build on a retina screen. Cropped image does not match cropped area at all.

It seems that scale is not handled correctly when generating `cropRect` (and the resulting croppedImage).

Note that any generated UIImage will have a scale of 2 on retina devices (ex: an image fetched online).

**Comment by romaincointepas** [comment]
It seems that you are hardcoding a scale of 1.0 here:
https://github.com/ruslanskorb/RSKImageCropper/blob/bc1b146e1befcd3e364b9ba3f05d3761e4b0b72c/RSKImageCropper/RSKImageCropViewController.m#L342

```
- (CGRect)cropRect
{
    CGRect cropRect = CGRectZero;
    float zoomScale = 1.0 / self.imageScrollView.zoomScale;
    
    cropRect.origin.x = round(self.imageScrollView.contentOffset.x * zoomScale);
    cropRect.origin.y = round(self.imageScrollView.contentOffset.y * zoomScale);
    cropRect.size.width = CGRectGetWidth(self.imageScrollView.bounds) * zoomScale;
    cropRect.size.height = CGRectGetHeight(self.imageScrollView.bounds) * zoomScale;
    
    cropRect = CGRectIntegral(cropRect);
    
    return cropRect;
}
```

I think you should be using originalImage.scale (https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/occ/instp/UIImage/scale)

**Comment by pronebird** [comment]
There is image view inside that takes care of retina. I don't think it image scale has anything to do with retina..

**Comment by romaincointepas** [comment]
I've made a video to show the problem with the provided example, but steps to reproduce above are pretty self-explanatory :)

http://cl.ly/37281l0W0h2E

**Comment by ruslanskorb** [comment]
@romaincointepas [Fixed!](https://github.com/ruslanskorb/RSKImageCropper/releases/tag/1.1.1)

**Comment by romaincointepas** [comment]
Amazing, thanks a lot!
