### ISSUE TITLE
DataSource Protocol stop working

### ISSUE THREAD

**Issue by AnthonyBY** [ruslanskorb/RSKImageCropper#46]
Hey Ruslan, 
I'm trying to changing radius in the maskRect (want to make it small), but it's looks like dataSource Protocol stop working. 

I use the following code:

 RSKImageCropViewController *imageCropVC = [[RSKImageCropViewController alloc] initWithImage:image];
    imageCropVC.delegate = self;
    imageCropVC.dataSource = self;
    [self presentViewController:imageCropVC animated:nil completion:nil];

delegate are working, but the dataSource are not. 

Could you please have a look? And yes, I have not forgot to add <RSKImageCropViewControllerDataSource> :)

Btw, thank you for the great framework!

Regards, 
Anton

**Comment by AnthonyBY** [comment]
Ruslan, I have found issue. When I init CropViewController with "cropMode" everything work fine. 

 RSKImageCropViewController *imageCropVC = [[RSKImageCropViewController alloc] initWithImage:image cropMode:RSKImageCropModeCircle];

Sorry for the inconvenience.

**Comment by ruslanskorb** [comment]
:thumbsup:
