### ISSUE TITLE
Should not the controller in RSKImageCropModeCircle return circled image?

### ISSUE THREAD

**Issue by maksTheAwesome** [ruslanskorb/RSKImageCropper#54]
I get squared image returned in the delegate even when the controller created in RSKImageCropModeCircle.

**Comment by ruslanskorb** [comment]
To get the circled image you need to set the value of the property `applyMaskToCroppedImage` to `YES`.

**Comment by maksTheAwesome** [comment]
Thanks, dude. I should have get that on my own.
