### ISSUE TITLE
Rectangle cropping with custom crop mask and avoidEmptySpaceAroundImage = YES

### ISSUE THREAD

**Issue by m1entus** [ruslanskorb/RSKImageCropper#58]
![ios simulator screen shot 3 lip 2015 20 42 30](https://cloud.githubusercontent.com/assets/1565368/8503718/1f7270ae-21c4-11e5-9c3d-13c5ba9cb663.png)
Hey, could you tell me how to calculate correct avoidness for empty space around image using rectangle, which formalus did you use to do it for Square, because it works perfectly fine!! If i am trying to do it for rectangle sometimes it doesn't avoid empty space. Help will be appreciated. Thanks.I attached image to see how it looks like

**Comment by ruslanskorb** [comment]
Hi @m1entus,
You need to calculate the movement rect. It is a custom rect in which the image can be moved.
Unfortunately, I have no formula to calculate it for the rectangle.
[Here](http://stackoverflow.com/questions/26824513/zoom-a-rotated-image-inside-scroll-view-to-fit-fill-frame-of-overlay-rect/28969133#28969133) you can see how I calculate it for the square.

**Comment by m1entus** [comment]
Yes, thanks for your answer i solved in but it is not perfect solution, and i just asked it before actually i did it, but anywat thanks.
