### ISSUE TITLE
Custom crop size at runtime

### ISSUE THREAD

**Issue by BalestraPatrick** [ruslanskorb/RSKImageCropper#6]
Hello,

Thanks a lot for the great library. I'd love to have support for a custom cropSize at runtime. You could simply add a boolean resizable variable and if it's set to true, the edges of the maskLayer can be dragged (to increase or decrease the width and the height of the mask).

Let me know if you are going to add this feature :)

Thanks.
Patrick

**Comment by ruslanskorb** [comment]
Bump. I'd like to hear from all watchers on this. Should RSKImageCropper support custom crop size at runtime? If yes, it's high time we make it happen.

Cheers,
Ruslan

**Comment by ruslanskorb** [comment]
Due to lack of demand for the community, a task is closed.
