### ISSUE TITLE
UIStatusBar color problem

### ISSUE THREAD

**Issue by Piero87** [ruslanskorb/RSKImageCropper#61]
Hi, i'm trying to use this amazing library, but i have a problem, when i dismiss the RSKImageCropperViewController the status bar become black, instead in my app i have a light color status bar. how i can fix it?

**Comment by ruslanskorb** [comment]
Hi @Piero87!
Sorry for the delay. Can you provide a test project? I think there should be no bugs.

**Comment by Piero87** [comment]
Hi @ruslanskorb, i have make a test project, as you can see in this project the status bar start light and then when i crop the image become dark.

i hope it helps, or maybe i have wrong something.

This is the project: https://www.dropbox.com/s/rlp0cqf5wtdpa0n/TestStatusBar.zip?dl=0

**Comment by ruslanskorb** [comment]
Hi @Piero87,
There are no problems with RSKImageCropper.
Simply add the following code to your view controller and everything will work well:
```obj-c
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    [UIApplication sharedApplication].statusBarStyle = UIStatusBarStyleLightContent;
}
```

**Comment by Piero87** [comment]
Thanks!
