### ISSUE TITLE
NSLocalizedString table and bundle name

### ISSUE THREAD

**Issue by tapz** [ruslanskorb/RSKImageCropper#62]
It would be nice to be able to provide table and bundle name, which RSKImageCropper would use in all NSLocalizedString calls. Currently with Pods localization is not possible.

**Comment by pronebird** [comment]
Would be even better to include a bundle with localizations and ship it with pod.

**Comment by tapz** [comment]
I can provide Finnish, Swedish and Spanish translations. Maybe some others too.

**Comment by ruslanskorb** [comment]
It sounds good to me! Can you do it and open a PR?

**Comment by heyehao2008** [comment]
I don't think  include too many NSLocalizedString in pods is good!

**Comment by tapz** [comment]
I what way localized string in a pod are not good? Anyway, I have already done a PR and if it's not merged I will continue using my own fork/branch.

**Comment by pronebird** [comment]
Defo having localization iniside of pod is a good practice.

**Comment by StevenMasini** [comment]
Hey guys, do we have a solution for the Localization ? I would need to add Mandarin.

**Comment by tapz** [comment]
I have it in my branch, but Ruslan hadn't merged the PR yet. You can add Mandarin to my branch if you like and I'll make a new PR:

https://github.com/tapz/RSKImageCropper/settings/collaboration

**Comment by StevenMasini** [comment]
The link doesn't works, it shows 404 not found.
But I would be glad to add the translation to your branch :)

**Comment by tapz** [comment]
Sorry, just remove the /settings/collaboration from the url:

https://github.com/tapz/RSKImageCropper

**Comment by StevenMasini** [comment]
Ok I pushed the Mandarin localization to the Localization branch. 
I can also provide you with Arabic, do you want it ?

**Comment by tapz** [comment]
I'm thankful for all possible languages :-) I actually took most of the languages from iPhone, but couldn't copy Chinese, Arabic etc because didn't know how to reproduce the characters and couldn't even recognise different characters.

**Comment by StevenMasini** [comment]
I asked a Pakistan friend who speak Arabic to translate these words. Nevertheless Arabic is read from right to left, not sure if we need to adapt the buttons for it.

**Comment by pronebird** [comment]
There was a presentation in one of WWDC sessions related to RTL languages and that iOS 9.0 automatically mirrors a lot of stuff. So as soon as we use trailing and leading constraints and such, I guess we're good.

**Comment by StevenMasini** [comment]
I'm not sure that Arabic users will notice the difference as long as the button are floating in the interface. Both LTR and RTL languages are "managed" it makes no difference.
Don't you think ?

**Comment by georgek1991** [comment]
Is there a way to not use the localisation from the pod and always set language to a single language ie. English.
