### ISSUE TITLE
Can we provide a maskRect that defined by a special image frame？

### ISSUE THREAD

**Issue by x137671075** [ruslanskorb/RSKImageCropper#64]

**Comment by ruslanskorb** [comment]
There is no special method to do it.
If you want to crop the image with the mask image I suggest you take a look at the function [`CGImageCreateWithMask`](https://developer.apple.com/library/prerelease/ios/documentation/GraphicsImaging/Reference/CGImage/index.html#//apple_ref/c/func/CGImageCreateWithMask).
