### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by SebastianMecklenburg** [ruslanskorb/RSKImageCropper#71]
Hi there,

I don't seem to be able to compile the example project due to podfile errors. 'pod install' ran fine, but xCode tells me

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

Do you know what this could mean?

Thanks and regards,
Sebastian Mecklenburg

**Comment by pronebird** [comment]
Just run pod install from Example folder as the message suggests.

**Comment by SebastianMecklenburg** [comment]
Sorry, I should have mentioned that I did that. Also tried `pod update` and deleting the pod related files and doing a fresh `pod init`. Stragely enough nothing worked.  That was at work where I use Xcode 7.0.1 under OSX 10.10.5. I just treid it on my home computer with Xcode 6.3 (also 10.10.5) and it worked fine. I will check at work again tomorrow, maybe I can find something out. Thanks for your help.

**Comment by ruslanskorb** [comment]
@SebastianMecklenburg I guess this error is related to the configuration of CocoaPods on your computer. You can try to find a solution [here](https://github.com/CocoaPods/CocoaPods/issues/2303).
