### ISSUE TITLE
RSKImageCrop for swift

### ISSUE THREAD

**Issue by virmaninupur5** [ruslanskorb/RSKImageCropper#72]
Hi ,

I installed this library using pods. Currently I am working on Xcode 7.0.1
After pod installation , I imported
 #import <RSKImageCropper/RSKImageCropper.h>  
in MyProject-Bridging-Header.h

It is showing an error No such module

**Comment by ruslanskorb** [comment]
Hi @virmaninupur5,

I think you have a problem with the configuration of the project. [Here](https://dl.dropboxusercontent.com/u/89891480/RSKImageCropperWithSwiftAndCocoapods.zip) you can see a working example.

Good luck!

**Comment by rajvinders** [comment]
I am facing this issue in swift 3.0.

**Comment by lis186** [comment]
@rajvinders 
You have to import RSKImageCrop by adding the code to your Project-Bridging-Header.h

`#import "RSKImageCropper/RSKImageCropper.h"`
