### ISSUE TITLE
Swift: Include of non-modular <tgmath.h>

### ISSUE THREAD

**Issue by oanta-william** [ruslanskorb/RSKImageCropper#75]
Hi, 

I'm trying to use your pod in my project that's developed using Swift, but after installing it I get the following error: 

/Users/william_oanta/Agilio/iOS-App/Pods/RSKImageCropper/RSKImageCropper/CGGeometry+RSKImageCropper.h:26:9: Include of non-modular header inside framework module 'RSKImageCropper.CGGeometry_RSKImageCropper'

I have set in Build Settings 'Allow Non-modular Includes in Framework Modules to YES for both the Live Vicarious and the Pods workspace, and it is still not working.

Here you have some screenshoots:

![screenshot 2015-10-21 13 58 34](https://cloud.githubusercontent.com/assets/13750935/10634712/6348b372-77fc-11e5-8d7c-2eb845aaa6e3.png)
![screenshot 2015-10-21 13 58 54](https://cloud.githubusercontent.com/assets/13750935/10634713/6349a9c6-77fc-11e5-9918-e54f5ba11bb3.png)
![screenshot 2015-10-21 13 59 28](https://cloud.githubusercontent.com/assets/13750935/10634711/63489cde-77fc-11e5-9eba-9081bfd26869.png)
![screenshot 2015-10-21 14 00 12](https://cloud.githubusercontent.com/assets/13750935/10634714/634ac8e2-77fc-11e5-9918-b55542019eee.png)
![screenshot 2015-10-21 14 00 34](https://cloud.githubusercontent.com/assets/13750935/10634716/63653092-77fc-11e5-8d00-60a69a125a01.png)

I have tried your demo example and it's working on the same environment - but I saw that you don't use Swift, and I guess this is a Swift caused problem. Any clue on how to fix it? 

Thanks

**Comment by shaase** [comment]
Hi there, just checking out this library myself. Have you set up a [bridging header](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) in your project? I'm trying the library out in a Swift project, and after adding `#import "RSKImageCropViewController.h"` to my header it appears to build without errors.

**Comment by ruslanskorb** [comment]
Hi @oanta-william,

I suppose that there is a problem with your CocoaPods configuration.
Try to use the latest stable version of CocoaPods (0.39.0).

[Here](https://dl.dropboxusercontent.com/u/89891480/RSKImageCropperWithSwiftCocoapodsAndModules.zip) you can see a working Swift project that uses CocoaPods and Framework Modules.

Cheers!
