### ISSUE TITLE
Connection to assetsd was interrupted or assetsd died

### ISSUE THREAD

**Issue by markfulo** [ruslanskorb/RSKImageCropper#82]
I have encountered this issue when I try to reload a panoramic image (10mb) in RSKImageCropViewController.

Steps:
1. Load pano image using UIImagePickerController with source type UIImagePickerControllerSourceTypePhotoLibrary.
2. Then "Choose" on RSKImageCropViewController (The UI lags here before going back to the previous view controller).
3. Cropped image is now assigned to the imageView.
4. Load again (back to step 1; with same image).

In step 4, I can see the image is displayed in the RSKImageCropViewController but now crashes. If I load images with lower file size, it can handle it.

I'm not sure where to handle this error or are there any workarounds on this?

Thank you.

(sorry, mistakenly pressed close issue)

**Comment by markfulo** [comment]
Also, I received memory warning sometimes on RSKImageCropViewController before it crashes, Most of the time it doesn't

**Comment by ruslanskorb** [comment]
Hi @markfulo,

Can you provide a test project?

p.s. I suggest you [to check the memory usage](https://developer.apple.com/library/ios/documentation/Performance/Conceptual/ManagingMemory/Articles/FindingPatterns.html#//apple_ref/doc/uid/20001882-CJBJFIDD) in your application.

**Comment by ruslanskorb** [comment]
@markfulo Have you fixed your issue?

**Comment by markfulo** [comment]
@ruslanskorb, sorry I haven't looked at it that much, currently I just implemented a temporary fix by limiting the file size of the image before I crop it. It's not on my priorities right now (my project has been changed >_< ).  I guess I'll close this for now. 

Awesome image cropper though! :+1:  :+1: 

Thanks!
