### ISSUE TITLE
Necessary variables are not accessible

### ISSUE THREAD

**Issue by mommyme** [ruslanskorb/RSKImageCropper#84]
I wanted to suggest that you make the following variables parameters, or at least make them available for change by including them in the .h file. I want to eliminate the space around my circle mask so that it fills the screen width-wise. Also, for iPhone 4S and showing the crop view controller in a popover in the iPad, the "move and scale" label is right on top of the crop area.

//static const CGFloat kPortraitCircleMaskRectInnerEdgeInset = 15.0f;
//static const CGFloat kPortraitSquareMaskRectInnerEdgeInset = 20.0f;
static const CGFloat kPortraitCircleMaskRectInnerEdgeInset = 0.0f;
static const CGFloat kPortraitSquareMaskRectInnerEdgeInset = 0.0f;
//static const CGFloat kPortraitMoveAndScaleLabelVerticalMargin = 64.0f;
static const CGFloat kPortraitMoveAndScaleLabelVerticalMargin = 30.0f;

//static const CGFloat kLandscapeCircleMaskRectInnerEdgeInset = 45.0f;
//static const CGFloat kLandscapeSquareMaskRectInnerEdgeInset = 45.0f;
static const CGFloat kLandscapeCircleMaskRectInnerEdgeInset = 0.0f;
static const CGFloat kLandscapeSquareMaskRectInnerEdgeInset = 0.0f;

**Comment by kevinvanderlugt** [comment]
:+1:  If I was to work on a PR for this feature, would you be interested in adding this as an enhancement?

**Comment by ruslanskorb** [comment]
Hi @kevinvanderlugt! Yes, I would.
