### ISSUE TITLE
Return the original image in the delegate methods

### ISSUE THREAD

**Issue by mommyme** [ruslanskorb/RSKImageCropper#85]
The cropped image is returned in the delegate method, but the original image is not returned. This is an issue if, for example, we call RSKImageCropper from

- (void)imagePickerController:(UIImagePickerController *)imagePicker didFinishPickingMediaWithInfo:(NSDictionary *)info

Unless we save the original image into a property at this point, we lose it. It would be a handy option to return the original image in the delegate method for RSKImageCropper.

**Comment by ruslanskorb** [comment]
For this purpose you can use the `originalImage` property of `RSKImageCropViewController` which is available in each method of `RSKImageCropViewControllerDelegate`.
