### ISSUE TITLE
Custom Image Cropper 

### ISSUE THREAD

**Issue by pacificanfog0** [ruslanskorb/RSKImageCropper#88]
Hello, I am trying to implement a UIImagePicker with custom cropper. I have searched for a similar error and the answer was "the imageCropViewControllerCustomMaskPath wasn't implemented", but I have implemented mine, so I'm not sure what's the issue here. Any help would be appreciated. Thanks in advance. 
    
    //UIImagePickerControllerDelegate
    func imagePickerController(picker: UIImagePickerController, didFinishPickingImage image: UIImage, editingInfo: [String : AnyObject]?) {
        
        picker.dismissViewControllerAnimated(true) { () -> Void in
            let imageCropVC = RSKImageCropViewController(image: image, cropMode: RSKImageCropMode.Custom)
            imageCropVC.delegate = self
            
            self.presentViewController(imageCropVC, animated: true, completion: nil)
        }
    }

    //RSKImageCropViewControllerDelegate, RSKImageCropViewControllerDataSource
    func imageCropViewControllerDidCancelCrop(controller: RSKImageCropViewController) {
        dismissViewControllerAnimated(true, completion: nil)
    }
    
    func imageCropViewController(controller: RSKImageCropViewController, didCropImage croppedImage: UIImage, usingCropRect cropRect: CGRect) {
        //Do some stuff here with the image.

        dismissViewControllerAnimated(true, completion: nil)
    }
    
    func imageCropViewControllerCustomMaskRect(controller: RSKImageCropViewController) -> CGRect {
        //let maskSize = CGSizeMake(320, 320)
        let maskRect = CGRectMake(0 , 30, 260, 260)
        return maskRect
    }
    
    func imageCropViewControllerCustomMaskPath(controller: RSKImageCropViewController) -> UIBezierPath {
        let rect = controller.maskRect
        let point1 = CGPointMake(CGRectGetMinX(rect), CGRectGetMaxY(rect))
        let point2 = CGPointMake(CGRectGetMaxX(rect), CGRectGetMaxY(rect))
        let point3 = CGPointMake(CGRectGetMidX(rect), CGRectGetMinY(rect))
        
        let triangle = UIBezierPath()
        triangle.moveToPoint(point1)
        triangle.moveToPoint(point2)
        triangle.moveToPoint(point3)
        triangle.closePath()
        
        return triangle;
    }
    
    func imageCropViewControllerCustomMovementRect(controller: RSKImageCropViewController) -> CGRect {
        let rect = controller.maskRect
        return rect;
    }

Error is: 

    Jan  4 19:54:40  App[10148] <Error>: CGAffineTransformInvert: singular matrix.
    Jan  4 19:54:40  App[10148] <Error>: CGAffineTransformInvert: singular matrix.
    Jan  4 19:54:40  App[10148] <Error>: CGAffineTransformInvert: singular matrix.

**Comment by ruslanskorb** [comment]
Hi @pacificanfog0,
You are missing the following code: `imageCropVC.dataSource = self`
Just add it and the error should disappear.

**Comment by sugitatestblue** [comment]
```
    func imageCropViewControllerCustomMaskPath(_ controller: RSKImageCropViewController) -> UIBezierPath {
        let rect = controller.maskRect
        let point1 = CGPoint(rect.minX, rect.maxY)
        let point2 = CGPoint(rect.maxX, rect.maxY)
        let point3 = CGPoint(rect.midX, rect.minY)

        let triangle = UIBezierPath()
        triangle.move(to: point1)
        triangle.move(to: point2)
        triangle.move(to: point3)
        triangle.close()

        return triangle;
    }
```
