### ISSUE TITLE
rotationAngle are not settable 

### ISSUE THREAD

**Issue by m1entus** [ruslanskorb/RSKImageCropper#91]
Could you make readwrite rotationAngle? I would like to reset angle during cropping, thanks.

**Comment by ruslanskorb** [comment]
Hi @m1entus,

I'm sorry to be late with the reply.

I plan to add the method `setRotationAngle:` to the category `RSKImageCropViewControllerProtectedMethods`. Will it solve your problem?

**Comment by m1entus** [comment]
Temporary by using Private extension for setter

**Comment by ruslanskorb** [comment]
I assume that the answer is "yes" :-]
