### ISSUE TITLE
How to adjust diameter of the circle?

### ISSUE THREAD

**Issue by jquiambao** [ruslanskorb/RSKImageCropper#97]
I've looked at all the properties in `RSKImageCropViewController` and can't find one that would adjust the diameter. Is this something available at the moment?

Ideally, it should adjust the size and maintain its center position on the screen. Thanks!

**Comment by jquiambao** [comment]
After RTFM, I realized that I need to use `RSKImageCropViewControllerDataSource` and set cropMode to `RSKImageCropModeCustom`. Then create my path manually.

I wish there was a way to just use `RSKImageCropModeCircle` and set a diameter. I'll give it a shot and submit a pull request.

**Comment by ruslanskorb** [comment]
There are two ways to achieve this.
1. Custom mask path `RSKImageCropModeCustom`.
2. Adjusting the properties `portraitCircleMaskRectInnerEdgeInset` and `landscapeCircleMaskRectInnerEdgeInset`.

**Comment by jquiambao** [comment]
@ruslanskorb `portraitCircleMaskRectInnerEdgeInset` is what I was looking for! thanks!
