### ISSUE TITLE
WhatsApp like image cropper.

### ISSUE THREAD

**Issue by mayur43s** [ruslanskorb/RSKImageCropper#99]
That's a very good control. Thanks for that.

**Improvements:** We can use this feature to implement WhatsApp like profile picture picker.

**Comment by ruslanskorb** [comment]
@mayur43s You may be interested in #89.

**Comment by mayur43s** [comment]
@ruslanskorb Will you be implementing that in next go?

**Comment by ruslanskorb** [comment]
I did not plan to do so in the near future. But you can do it yourself in the subclass of `RSKImageCropViewController`.
